#!/bin/bash
#
#SBATCH -p normal # partition (queue)
#SBATCH -N 1 # number of nodes
#SBATCH -J run-pleioFDR
#SBATCH --mem 300G # memory pool for all cores
#SBATCH -t 9-23:59 # time (D-HH:MM)
#SBATCH -o ./real/outputs/log.%j.out # STDOUT
#SBATCH -e ./real/outputs/log.%j.err # STDERR
#SBATCH --mail-type=FAIL # notifications for job fail
#SBATCH --mail-user=claudia.vasallo@upf.edu # send-to address


# Modules
module load Python/3.6.6-foss-2018b
module load MATLAB/2020a


# Config
COMBI_LIST=$1
MAT_DIR=$2
OUTPUT_DIR=$(readlink -f $3) # Convert to absolute path
PLEIOFDR_DIR=/gpfs42/projects/lab_anavarro/disease_pleiotropies/LifespanPleiotropies_2/software/pleiofdr/
ORIGINAL_CONFIG_FILE='./real/inputs/config_base.txt'
MAT_SUMSTATS_DIR=$(readlink -f ${MAT_DIR}) #full path
CONFIG_FILE_DIR=$(readlink -f   ${OUTPUT_DIR}) #full path

REFERENCE_FILE=/gpfs42/projects/lab_anavarro/disease_pleiotropies/LifespanPleiotropies_2/data/1000G-SNPs.ref.gz


# Array Dependent Config
# If there is no array number assigned:
#   - that means that the script is being executed directly.
#   - it takes the first item of the list as a parameter
# If there is an array number assigned:
#   - that means that the script is being executed through the cluster
#   - it takes the item correspondent to the array number
if [ "${SLURM_ARRAY_TASK_ID}" == "" ]
then
  INPUT_FILE=$(cat "${COMBI_LIST}" | sed -n 1p)
  FILE1=(`cat ${COMBI_LIST} | sed -n 1p | cut -d ' ' -f 1`)
  FILE2=(`cat ${COMBI_LIST} | sed -n 1p | cut -d ' ' -f 2`)
  CODE1=$(basename ${FILE1} | cut -d '.' -f1)
  CODE2=$(basename ${FILE2} | cut -d '.' -f1)
else
  INPUT_FILE=$(cat "${COMBI_LIST}" | sed -n ${SLURM_ARRAY_TASK_ID}p)
  FILE1=(`cat ${COMBI_LIST} | sed -n ${SLURM_ARRAY_TASK_ID}p | cut -d ' ' -f 1`)
  FILE2=(`cat ${COMBI_LIST} | sed -n ${SLURM_ARRAY_TASK_ID}p | cut -d ' ' -f 2`)
  CODE1=$(basename ${FILE1} | cut -d '.' -f1)
  CODE2=$(basename ${FILE2} | cut -d '.' -f1)
fi


# Execution
## Creates Matlab Sumstats for trait
#bash ./real/scripts/create-matlab-sumstats.sh \
#        ${FILE1} \
#        ${TMP_DIR} \


# Creates output directory
mkdir ${OUTPUT_DIR}/${CODE1}:${CODE2}

# Creates config file
python ./real/scripts/9-pleiodetect_files.py \
    ${CODE1} \
    ${CODE2} \
    ${ORIGINAL_CONFIG_FILE} \
    ${MAT_SUMSTATS_DIR} \
    ${OUTPUT_DIR} \
    ${CONFIG_FILE_DIR}

CONFIG_FILE=$(readlink -f ${CONFIG_FILE_DIR}/${CODE1}:${CODE2}.config.txt) # full path


# Executes pleioFDR under matlab
matlab -nosplash -nodesktop -nodisplay \
	-r "config='${CONFIG_FILE}'; \
		  run('${PLEIOFDR_DIR}/runme.m'); \
		  quit"




# Create result.csv from result.mat
# Transforms result.mat generated by pleioFDR into a csv file
python ./real/scripts/mat-to-csv.py \
       ${OUTPUT_DIR}/${CODE1}:${CODE2}/result.mat \
       ${OUTPUT_DIR}/${CODE1}:${CODE2}/result.csv \
       ${REFERENCE_FILE}


#python /gpfs42/projects/lab_anavarro/disease_pleiotropies/LifespanPleiotropies_2/software/python_convert/sumstats.py \
#    mat-to-csv \
#    --force \
#    --mat ${OUTPUT_DIR}/${CODE1}:${CODE2}/result.mat \
#    --ref ${REFERENCE_FILE} \
#    --out ${OUTPUT_DIR}/${CODE1}:${CODE2}/result.csv




# Merges pleioFDR esults with original sumstats to retrieve zscore values
# with this we have all SNPs results and not only significant ones, useful for
# MAGMA and for separating clumping by concordant, discordant, etc

RES=${OUTPUT_DIR}/${CODE1}:${CODE2}/result.csv
MAT1=${MAT_DIR}/${CODE1}.mat.csv
MAT2=${MAT_DIR}/${CODE2}.mat.csv  
python ./real/scripts/zscores_add.py ${RES} ${MAT1} ${MAT2} ${CODE1} ${CODE2} ${OUTPUT_DIR}/${CODE1}:${CODE2}


# Removes tmp files
#rm ${MAT_SUMSTATS_DIR}/${TRAIT_CODE}.mat
#rm ${MAT_SUMSTATS_DIR}/${CODE1}.mat
#rm ${MAT_SUMSTATS_DIR}/${CODE2}.mat
#rm ${MAT_SUMSTATS_DIR}/${TRAIT_CODE}.csv
#rm ${MAT_SUMSTATS_DIR}/${CODE1}.csv
#rm ${MAT_SUMSTATS_DIR}/${CODE2}.csv

