##############################################################################################################################
##                                                                                                                          ##
## Analyse independent SNP effects for dataset1 and dataset2 using R                                                        ##
##                                                                                                                          ##
## This script provides local installation and flexible permutation of heatmap p-values                                    ##
## using the "independent_aligned_effects.txt" file generated by SECA or iSECA                                              ##
##                                                                                                                          ##
## Coded by Dale R Nyholt, dale.nyholt@qimr.edu.au                                                                          ##
##                                                                                                                          ##
## Nyholt DR (2013) SECA: SNP effect concordance analysis using genome-wide association summary results. [in preparation]   ##
##                                                                                                                          ##
##                                                                                                                          ##
## Note: the permuted heatmap p-values are only as accurate as the number of replicates, for example:                       ##
##        6 /  101 = 0.059 ; 95%CI = 0.02750813 - 0.12359110                                                                ##
##       51 / 1001 = 0.051 ; 95%CI = 0.03896177 - 0.06636973                                                                ##
##       36 / 1001 = 0.036 ; 95%CI = 0.02608937 - 0.04938667                                                                ##
##       Hence, 1000 permutations are sufficient to indicate pointwise significance                                         ##
##       and whether more permutations are desired to give a 95%CI which does not include 0.05.                             ##
##                                                                                                                          ##
##       10000 permutations are preferable, but would unnecessarily take too long (if there is no trend):                   ##
##       501/10001 = 0.050 ; 95%CI = 0.04598980 - 0.05454568                                                                ##
##       461/10001 = 0.046 ; 95%CI = 0.04215709 - 0.05038225                                                                ##
##                                                                                                                          ##
## Therefore, this script is provided for USERS to adjust the number or replicates by changing the following number         ##
## assigned to the below "reps" variable                                                                                    ##
reps<-1000                                                                                                                  ##
##                                                                                                                          ##
## To run the permutations simply source this script from within R:                                                         ##
## source("SECA_Ranalysis.R")                                                                                               ##
##                                                                                                                          ##
## or run using R's BATCH command:                                                                                          ##
## R CMD BATCH SECA_Ranalysis.R                                                                                             ##
##                                                                                                                          ##
## in the same directory as your "independent_aligned_effects.txt" file                                                     ##
##                                                                                                                          ##
## Results are written to "SECA_results.txt"                                                                                ##
##                                                                                                                          ##
## For more details, please refer to the SECA webpage, http://neurogenetics.qimrberghofer.edu.au/SECA/                      ##
##                                                                                                                          ##
##############################################################################################################################





####################################			RUN			###################################$






################################################################################################################$
#library(data.table)

args <- commandArgs(T)

iae_file <- args[1]
code <- args[2]
outdir <- args[3]

setwd(outdir)



message("Starting .... relax takes a while")


## Read in the "independent_aligned_effects.txt" data for analysis (as generated by SECA or iSECA):


data1.0P1 <- read.table(iae_file, header=T)

#data1.0P1 <- fread(iae_file, header=T)

sids <- strsplit(code, ":", fixed=TRUE)[[1]]

# Change column names to standard ones used
for (ni in 1:length(sids)) {
colnames(data1.0P1)[colnames(data1.0P1)==paste0("BETA_", sids[ni])] <- paste0("BETA", ni)
colnames(data1.0P1)[colnames(data1.0P1)==paste0("EFF_", sids[ni])] <- paste0("EFF", ni)
colnames(data1.0P1)[colnames(data1.0P1)==paste0("P_", sids[ni])] <- paste0("P", ni)
}

## set options(error=expression(NULL)) to ignore all errors (otherwise an error will stop the BATCH script):
options(error=expression(NULL))


## Create function to rotate 2x2 tables 180 degrees:
rotate_matrix_180 <- function(x) "[<-"(x, , rev(x))


## Record the total number of independent aligned SNPs:
totalSNPs<-nrow(data1.0P1)

##############################################################################################################################

## Perform grid search to find minimum fisher's (effect concordance) and binomial (pleiotropy) test p-values

Psteps1<-NULL
increment1<-0.01
for(i in 1:100) 
{
  Psteps1[i]<-1.01 - increment1
  increment1<-increment1 + 0.01
}

Psteps2<-NULL
increment2<-0.001
for(i in 1:9) 
{
  Psteps2[i]<-0.01 - increment2
  increment2<-increment2 + 0.001
}

Psteps3<-Psteps2/10
Psteps4<-Psteps2/100
Psteps5<-Psteps2/1000
Psteps6<-Psteps2/10000
Psteps7<-(Psteps2/100000)[1:5]

PstepsALL<-c(Psteps1, Psteps2, Psteps3, Psteps4, Psteps5, Psteps6, Psteps7)

NumPstepsALL<-length(PstepsALL)

BTpvalues<-matrix(nrow=NumPstepsALL, ncol=NumPstepsALL)
FTpvalues<-matrix(nrow=NumPstepsALL, ncol=NumPstepsALL)

gridrows<-NumPstepsALL*NumPstepsALL
gridP1threshold<-matrix(nrow=gridrows, ncol=1)
gridP2threshold<-matrix(nrow=gridrows, ncol=1)
gridBTcountP1P2<-matrix(nrow=gridrows, ncol=1)
gridBTcountP1<-matrix(nrow=gridrows, ncol=1)
gridBTcountP2<-matrix(nrow=gridrows, ncol=1)
gridBTobsProps<-matrix(nrow=gridrows, ncol=1)
gridBTexpProps<-matrix(nrow=gridrows, ncol=1)
gridBTobsPropOverExpProps<-matrix(nrow=gridrows, ncol=1)
gridBTpvalues<-matrix(nrow=gridrows, ncol=1)
gridFTminusminus<-matrix(nrow=gridrows, ncol=1)
gridFTplusminus<-matrix(nrow=gridrows, ncol=1)
gridFTminusplus<-matrix(nrow=gridrows, ncol=1)
gridFTplusplus<-matrix(nrow=gridrows, ncol=1)
gridFToddsRatios<-matrix(nrow=gridrows, ncol=1)
gridFTpvalues<-matrix(nrow=gridrows, ncol=1)


gridrow<-0
for(j in 1:NumPstepsALL) 
{
  for(k in 1:NumPstepsALL) 
  {
    gridrow<-gridrow + 1
    gridP1threshold[gridrow]<-signif(PstepsALL[j], digits=3)
    gridP2threshold[gridrow]<-signif(PstepsALL[k], digits=3)
  }
}

gridrow<-0
for(j in 1:NumPstepsALL) 
{
  dataP1grid<-subset(data1.0P1, P1 <= PstepsALL[j]) 
  for(k in 1:NumPstepsALL) 
  {
    dataP2grid<-subset(data1.0P1, P2 <= PstepsALL[k]) 
    dataP1P2grid<-subset(dataP1grid, P2 <= PstepsALL[k]) 

    gridrow<-gridrow + 1
    gridBTcountP1[gridrow]<-nrow(dataP1grid)
    gridBTcountP2[gridrow]<-nrow(dataP2grid)
    gridBTcountP1P2[gridrow]<-nrow(dataP1P2grid)

    dataP1P2grid_BT<-binom.test(gridBTcountP1P2[gridrow],gridBTcountP1[gridrow], alternative ="two.sided", p = gridBTcountP2[gridrow]/totalSNPs)

    FTtable_tmp<-table(dataP1P2grid[c("EFF1","EFF2")])
    FTtable<-(FTtable_tmp + rotate_matrix_180(FTtable_tmp))/2
    dataP1P2grid_FT<-fisher.test(FTtable, alternative ="two.sided")

    BTpvalues[j,k]<-dataP1P2grid_BT$p.value
    FTpvalues[j,k]<-dataP1P2grid_FT$p.value
    
    gridBTobsProps[gridrow]<-round((dataP1P2grid_BT[[5]]), digits=4)
    gridBTexpProps[gridrow]<-round((dataP1P2grid_BT[[6]]), digits=4)
    gridBTobsPropOverExpProps[gridrow]<-signif((dataP1P2grid_BT[[5]])/(dataP1P2grid_BT[[6]]), digits=4)
    gridBTpvalues[gridrow]<-signif(dataP1P2grid_BT[[3]], digits=4)

    gridFTminusminus[gridrow]<-FTtable[1]
    gridFTplusminus[gridrow]<-FTtable[2]
    gridFTminusplus[gridrow]<-FTtable[3]    
    gridFTplusplus[gridrow]<-FTtable[4]
    gridFToddsRatios[gridrow]<-signif(dataP1P2grid_FT[[3]][1], digits=4)
    gridFTpvalues[gridrow]<-signif(dataP1P2grid_FT[[1]], digits=4)
  }
}

gridBTobsProps<-formatC(gridBTobsProps, format="f", digits=3) 
gridBTobsPropOverExpProps<-format(gridBTobsPropOverExpProps, format="f", digits=3) 
gridBTpvalues<-format(gridBTpvalues, format="f", digits=3, scientific = TRUE) 
gridFToddsRatios<-format(gridFToddsRatios, format="f", digits=3) 
gridFTpvalues<-format(gridFTpvalues, format="f", digits=3, scientific = TRUE) 

griddata.table<-cbind(gridP1threshold,gridP2threshold,gridBTcountP1,gridBTcountP2,gridBTcountP1P2,gridBTobsProps,gridBTexpProps,gridBTobsPropOverExpProps,gridBTpvalues,gridFTminusminus,gridFTplusminus,gridFTminusplus,gridFTplusplus,gridFToddsRatios,gridFTpvalues)
colnames(griddata.table)<-c("P1", "P2", "P1snp", "P2snp", "P1P2snp", "PropO", "PropE", "RatioOE", "BtestPval", "--", "+-", "-+", "++", "FtestOR", "FtestPval")


write.table(griddata.table, file="griddata.txt", quote = FALSE, sep = "\t", row.names = FALSE, col.names = TRUE)


##############################################################################################################################

## Generate BT and FT heatmap PLOTs for P1 <= {0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0}
## For Binomial test plot the RATIO (obs/exp proportion) and p-values
## For Fisher's test plot the OR and p-values

## Prepare data for plotting

#Psteps1plot<-rev(c(0.01,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0))
Psteps1plot<-c(1,0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1,0.05,0.01)
Psteps2plot<-c(0.01,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)

NumPsteps12plot<-length(Psteps1plot)

plotP1threshold<-matrix(nrow=NumPsteps12plot, ncol=NumPsteps12plot)
plotP2threshold<-matrix(nrow=NumPsteps12plot, ncol=NumPsteps12plot)

BTratioOEs_1plus0.05_heatmap_input<-matrix(nrow=NumPsteps12plot, ncol=NumPsteps12plot)
FTors_1plus0.05_heatmap_input<-matrix(nrow=NumPsteps12plot, ncol=NumPsteps12plot)

for(j in 1:NumPsteps12plot) 
{
  dataP1plot<-subset(data1.0P1, P1 <= Psteps1plot[j]) 
  for(k in 1:NumPsteps12plot)
  {
    dataP2plot<-subset(data1.0P1, P2 <= Psteps2plot[k]) 
    dataP1P2plot<-subset(dataP1plot, P2 <= Psteps2plot[k]) 

    plotBTcountP1<-nrow(dataP1plot)
    plotBTcountP2<-nrow(dataP2plot)
    plotBTcountP1P2<-nrow(dataP1P2plot)
    #dataP1P2plot_BT<-binom.test(plotBTcountP1P2,plotBTcountP1, alternative ="greater", p = plotBTcountP2/totalSNPs)
    dataP1P2plot_BT<-binom.test(plotBTcountP1P2,plotBTcountP1, alternative ="two.sided", p = plotBTcountP2/totalSNPs)

    BTratioOE<-dataP1P2plot_BT[[5]]/dataP1P2plot_BT[[6]]

    BTratioOEs_1plus0.05_heatmap_input[j,k]<-if(dataP1P2plot_BT$p.value <= 0.05 & BTratioOE >= 1) { 4 }
                                        else if(dataP1P2plot_BT$p.value  > 0.05 & BTratioOE >= 1) { 3 }
                                        else if(dataP1P2plot_BT$p.value  > 0.05 & BTratioOE < 1) { 2 }                                       
                                        else if(dataP1P2plot_BT$p.value <= 0.05 & BTratioOE < 1) { 1 }

    FTtableplot_tmp<-table(dataP1P2plot[c("EFF1","EFF2")])
    FTtableplot<-( FTtableplot_tmp + rotate_matrix_180(FTtableplot_tmp) )/2
    dataP1P2plot_FT<-fisher.test(FTtableplot, alternative ="two.sided")
    FTors_1plus0.05_heatmap_input[j,k]<-if(dataP1P2plot_FT$p.value <= 0.05 & dataP1P2plot_FT$estimate >= 1) { 4 }
                                        else if(dataP1P2plot_FT$p.value > 0.05 & dataP1P2plot_FT$estimate >= 1) { 3 }
                                        else if(dataP1P2plot_FT$p.value > 0.05 & dataP1P2plot_FT$estimate < 1) { 2 }                                       
                                        else if(dataP1P2plot_FT$p.value <= 0.05 & dataP1P2plot_FT$estimate < 1) { 1 }
  }
}

rownames(BTratioOEs_1plus0.05_heatmap_input)<-Psteps1plot
colnames(BTratioOEs_1plus0.05_heatmap_input)<-Psteps2plot

rownames(FTors_1plus0.05_heatmap_input)<-Psteps1plot
colnames(FTors_1plus0.05_heatmap_input)<-Psteps2plot


ORtypes<-names(table(FTors_1plus0.05_heatmap_input))

if(length(ORtypes) == 4) { FT.heat.colors<-c("darkgreen", "lightgreen", "orange", "red") }

if(length(ORtypes) == 3) 
{
       if(ORtypes[1] == "1" & ORtypes[2] == "2" & ORtypes[3] == "3") { FT.heat.colors<-c("darkgreen" , "lightgreen", "orange") }
  else if(ORtypes[1] == "1" & ORtypes[2] == "2" & ORtypes[3] == "4") { FT.heat.colors<-c("darkgreen" , "lightgreen", "red") }
  else if(ORtypes[1] == "1" & ORtypes[2] == "3" & ORtypes[3] == "4") { FT.heat.colors<-c("darkgreen" , "orange"    , "red") }
  else if(ORtypes[1] == "2" & ORtypes[2] == "3" & ORtypes[3] == "4") { FT.heat.colors<-c("lightgreen", "orange"    , "red") }
}

if(length(ORtypes) == 2) 
{
       if(ORtypes[1] == "1" & ORtypes[2] == "2")                     { FT.heat.colors<-c("darkgreen" , "lightgreen") }
  else if(ORtypes[1] == "1" & ORtypes[2] == "3")                     { FT.heat.colors<-c("lightgreen", "orange") }
  else if(ORtypes[1] == "1" & ORtypes[2] == "4")                     { FT.heat.colors<-c("darkgreen" , "red") }
  else if(ORtypes[1] == "2" & ORtypes[2] == "3")                     { FT.heat.colors<-c("lightgreen", "orange") }
  else if(ORtypes[1] == "2" & ORtypes[2] == "4")                     { FT.heat.colors<-c("lightgreen", "red") }
  else if(ORtypes[1] == "3" & ORtypes[2] == "4")                     { FT.heat.colors<-c("orange"    , "red") }
}

if(length(ORtypes) == 1) 
{
       if(ORtypes[1] == "1")                                         { FT.heat.colors<-c("darkgreen") }
  else if(ORtypes[1] == "2")                                         { FT.heat.colors<-c("lightgreen") }
  else if(ORtypes[1] == "3")                                         { FT.heat.colors<-c("orange") }
  else if(ORtypes[1] == "4")                                         { FT.heat.colors<-c("red") }
}


RATIOtypes<-names(table(BTratioOEs_1plus0.05_heatmap_input))

if(length(RATIOtypes) == 4) { BT.heat.colors<-c("darkgreen", "lightgreen", "orange", "red") }

if(length(RATIOtypes) == 3) 
{
       if(RATIOtypes[1] == "1" & RATIOtypes[2] == "2" & RATIOtypes[3] == "3") { BT.heat.colors<-c("darkgreen" , "lightgreen", "orange") }
  else if(RATIOtypes[1] == "1" & RATIOtypes[2] == "2" & RATIOtypes[3] == "4") { BT.heat.colors<-c("darkgreen" , "lightgreen", "red") }
  else if(RATIOtypes[1] == "1" & RATIOtypes[2] == "3" & RATIOtypes[3] == "4") { BT.heat.colors<-c("darkgreen" , "orange"    , "red") }
  else if(RATIOtypes[1] == "2" & RATIOtypes[2] == "3" & RATIOtypes[3] == "4") { BT.heat.colors<-c("lightgreen", "orange"    , "red") }
}

if(length(RATIOtypes) == 2) 
{
       if(RATIOtypes[1] == "1" & RATIOtypes[2] == "2")                     { BT.heat.colors<-c("darkgreen" , "lightgreen") }
  else if(RATIOtypes[1] == "1" & RATIOtypes[2] == "3")                     { BT.heat.colors<-c("lightgreen", "orange") }
  else if(RATIOtypes[1] == "1" & RATIOtypes[2] == "4")                     { BT.heat.colors<-c("darkgreen" , "red") }
  else if(RATIOtypes[1] == "2" & RATIOtypes[2] == "3")                     { BT.heat.colors<-c("lightgreen", "orange") }
  else if(RATIOtypes[1] == "2" & RATIOtypes[2] == "4")                     { BT.heat.colors<-c("lightgreen", "red") }
  else if(RATIOtypes[1] == "3" & RATIOtypes[2] == "4")                     { BT.heat.colors<-c("orange"    , "red") }
}

if(length(RATIOtypes) == 1) 
{
       if(RATIOtypes[1] == "1")                                         { BT.heat.colors<-c("darkgreen") }
  else if(RATIOtypes[1] == "2")                                         { BT.heat.colors<-c("lightgreen") }
  else if(RATIOtypes[1] == "3")                                         { BT.heat.colors<-c("orange") }
  else if(RATIOtypes[1] == "4")                                         { BT.heat.colors<-c("red") }
}


gridline_positions<-c(0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5)

heatmap_dale<-function (x, Rowv = NULL, Colv = if (symm) "Rowv" else NULL, 
    distfun = dist, hclustfun = hclust, reorderfun = function(d, 
        w) reorder(d, w), add.expr, symm = FALSE, revC = identical(Colv, 
        "Rowv"), scale = c("row", "column", "none"), na.rm = TRUE, 
    margins = c(5, 5, 5, 5), ColSideColors, RowSideColors, cexRow = 0.2 + 
        1/log10(nr), cexCol = 0.2 + 1/log10(nc), labRow = NULL, 
    labCol = NULL, main = NULL, xlab = NULL, ylab = NULL, keep.dendro = FALSE, 
    verbose = getOption("verbose"), ...) 
{
    scale <- if (symm && missing(scale)) 
        "none"
    else match.arg(scale)
    if (length(di <- dim(x)) != 2 || !is.numeric(x)) 
        stop("'x' must be a numeric matrix")
    nr <- di[1L]
    nc <- di[2L]
    if (nr <= 1 || nc <= 1) 
        stop("'x' must have at least 2 rows and 2 columns")
    if (!is.numeric(margins) || length(margins) != 4L) 
        stop("'margins' must be a numeric vector of length 4")
    doRdend <- !identical(Rowv, NA)
    doCdend <- !identical(Colv, NA)
    if (!doRdend && identical(Colv, "Rowv")) 
        doCdend <- FALSE
    if (is.null(Rowv)) 
        Rowv <- rowMeans(x, na.rm = na.rm)
    if (is.null(Colv)) 
        Colv <- colMeans(x, na.rm = na.rm)
    if (doRdend) {
        if (inherits(Rowv, "dendrogram")) 
            ddr <- Rowv
        else {
            hcr <- hclustfun(distfun(x))
            ddr <- as.dendrogram(hcr)
            if (!is.logical(Rowv) || Rowv) 
                ddr <- reorderfun(ddr, Rowv)
        }
        if (nr != length(rowInd <- order.dendrogram(ddr))) 
            stop("row dendrogram ordering gave index of wrong length")
    }
    else rowInd <- 1L:nr
    if (doCdend) {
        if (inherits(Colv, "dendrogram")) 
            ddc <- Colv
        else if (identical(Colv, "Rowv")) {
            if (nr != nc) 
                stop("Colv = \"Rowv\" but nrow(x) != ncol(x)")
            ddc <- ddr
        }
        else {
            hcc <- hclustfun(distfun(if (symm) 
                x
            else t(x)))
            ddc <- as.dendrogram(hcc)
            if (!is.logical(Colv) || Colv) 
                ddc <- reorderfun(ddc, Colv)
        }
        if (nc != length(colInd <- order.dendrogram(ddc))) 
            stop("column dendrogram ordering gave index of wrong length")
    }
    else colInd <- 1L:nc
    x <- x[rowInd, colInd]
    labRow <- if (is.null(labRow)) 
        if (is.null(rownames(x))) 
            (1L:nr)[rowInd]
        else rownames(x)
    else labRow[rowInd]
    labCol <- if (is.null(labCol)) 
        if (is.null(colnames(x))) 
            (1L:nc)[colInd]
        else colnames(x)
    else labCol[colInd]
    if (scale == "row") {
        x <- sweep(x, 1L, rowMeans(x, na.rm = na.rm), check.margin = FALSE)
        sx <- apply(x, 1L, sd, na.rm = na.rm)
        x <- sweep(x, 1L, sx, "/", check.margin = FALSE)
    }
    else if (scale == "column") {
        x <- sweep(x, 2L, colMeans(x, na.rm = na.rm), check.margin = FALSE)
        sx <- apply(x, 2L, sd, na.rm = na.rm)
        x <- sweep(x, 2L, sx, "/", check.margin = FALSE)
    }
    lmat <- rbind(c(NA, 3), 2:1)
    lwid <- c(if (doRdend) 1 else 0.05, 4)
    lhei <- c((if (doCdend) 1 else 0.05) + if (!is.null(main)) 0.2 else 0, 
        4)
    if (!missing(ColSideColors)) {
        if (!is.character(ColSideColors) || length(ColSideColors) != 
            nc) 
            stop("'ColSideColors' must be a character vector of length ncol(x)")
        lmat <- rbind(lmat[1, ] + 1, c(NA, 1), lmat[2, ] + 1)
        lhei <- c(lhei[1L], 0.2, lhei[2L])
    }
    if (!missing(RowSideColors)) {
        if (!is.character(RowSideColors) || length(RowSideColors) != 
            nr) 
            stop("'RowSideColors' must be a character vector of length nrow(x)")
        lmat <- cbind(lmat[, 1] + 1, c(rep(NA, nrow(lmat) - 1), 
            1), lmat[, 2] + 1)
        lwid <- c(lwid[1L], 0.2, lwid[2L])
    }
    lmat[is.na(lmat)] <- 0
    if (verbose) {
        cat("layout: widths = ", lwid, ", heights = ", lhei, 
            "; lmat=\n")
        print(lmat)
    }
    dev.hold()
    on.exit(dev.flush())
    op <- par(no.readonly = TRUE)
    on.exit(par(op), add = TRUE)
    layout(lmat, widths = lwid, heights = lhei, respect = TRUE)
    if (!missing(RowSideColors)) {
        par(mar = c(margins[1L], margins[2L], margins[3L], margins[4L]))
        image(rbind(1L:nr), col = RowSideColors[rowInd], axes = FALSE)
    }
    if (!missing(ColSideColors)) {
        par(mar = c(margins[1L], margins[2L], margins[3L], margins[4L]))
        image(cbind(1L:nc), col = ColSideColors[colInd], axes = FALSE)
    }
    par(mar = c(margins[1L], margins[2L], margins[3L], margins[4L]))
    if (!symm || scale != "none") 
        x <- t(x)
    if (revC) {
        iy <- nr:1
        if (doRdend) 
            ddr <- rev(ddr)
        x <- x[, iy]
    }
    else iy <- 1L:nr
    par(oma=margins+c(-4,-4,-0.5,9))
    image(1L:nc, 1L:nr, x, xlim = 0.5 + c(0, nc), ylim = 0.5 + 
        c(0, nr), axes = FALSE, xlab = "", ylab = "", ...)
    axis(1, 1L:nc, labels = labCol, las = 1, line = -0.5, tick = 0, 
        cex.axis = cexCol)
    if (!is.null(xlab)) 
        mtext(xlab, side = 1, line = margins[1L] - 1.5)
    axis(2, iy, labels = labRow, las = 2, line = -0.5, tick = 0, 
        cex.axis = cexRow)
    if (!is.null(ylab)) 
        mtext(ylab, side = 2, line = margins[2L] - 0.25)
    if (!missing(add.expr)) 
        eval(substitute(add.expr))
    par(mar = c(0, 0, 1, 0))
    if (doRdend) 
        plot(ddr, horiz = TRUE, axes = FALSE, yaxs = "i", leaflab = "none")
    else frame()
    par(mar = c(0, 0, if (!is.null(main)) 2 else 0, 0))
    if (doCdend) 
        plot(ddc, axes = FALSE, xaxs = "i", leaflab = "none")
    else if (!is.null(main)) 
        frame()
    if (!is.null(main)) {
        par(xpd = T)
        title(main, cex.main = 1 * op[["cex.main"]])
    }
    invisible(list(rowInd = rowInd, colInd = colInd, Rowv = if (keep.dendro && 
        doRdend) ddr, Colv = if (keep.dendro && doCdend) ddc))
}


pdf(file="FTheatmap.pdf", bg = "white", width = 9, height = 7)
heatmap_margins=c(4.5,4,1.5,2)
#par(oma=heatmap_margins+c(-4,-4,-1,9))
heatmap_dale(as.matrix(FTors_1plus0.05_heatmap_input), Rowv=NA, Colv="Rowv", scale="none", margins=heatmap_margins, 
main = "Fisher's tests for association of SNP effect direction between the two datasets", 
xlab = "P-value threshold in dataset2 (P2)", ylab = "P-value threshold in dataset1 (P1)", 
cexRow = 0.95, cexCol = 0.95,
col = FT.heat.colors, add.expr = abline(h=gridline_positions, v=gridline_positions))

legend("right", inset=0.0, c(expression(paste("OR" >= "1, ", "P" <= "0.05")), 
expression(paste("OR" >= "1, ", "P" > "0.05")), expression(paste("OR" < "1, ", "P" > "0.05")), 
expression(paste("OR" < "1, ", "P" <= "0.05"))),
fill=c("red","orange", "lightgreen", "darkgreen"), horiz=FALSE)

dev.off()


pdf(file="BTheatmap.pdf", bg = "white", width = 9, height = 7)
heatmap_margins=c(4.5,4,1.5,2)
#par(oma=heatmap_margins+c(-4,-4,-1,9))
heatmap_dale(as.matrix(BTratioOEs_1plus0.05_heatmap_input), Rowv=NA, Colv="Rowv", scale="none", margins=heatmap_margins, 
main = "Binomial tests for genetic overlap of SNPs between the two datasets (pleiotropy)", 
xlab = "P-value threshold in dataset2 (P2)", ylab = "P-value threshold in dataset1 (P1)", 
cexRow = 0.95, cexCol = 0.95,
col = BT.heat.colors, add.expr = abline(h=gridline_positions, v=gridline_positions))

legend("right", inset=0.0, c(expression(paste("Obs" >= "Exp, ", "P" <= "0.05")), 
expression(paste("Obs" >= "Exp, ", "P" > "0.05")), expression(paste("Obs" < "Exp, ", "P" > "0.05")), 
expression(paste("Obs" < "Exp, ", "P" <= "0.05"))),
fill=c("red","orange", "lightgreen", "darkgreen"), horiz=FALSE)

dev.off()


##############################################################################################################################

## Prepare Binomial and Fisher's test heatmap plot data for export:

Pstepsplotgrid<-c(1,0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1,0.05,0.01)

NumPstepsplotgrid<-length(Pstepsplotgrid)

plotgridFTors_sq<-matrix(nrow=NumPstepsplotgrid, ncol=NumPstepsplotgrid)
plotgridFTpvalues_sq<-matrix(nrow=NumPstepsplotgrid, ncol=NumPstepsplotgrid)

plotgridBTratioOEs_sq<-matrix(nrow=NumPstepsplotgrid, ncol=NumPstepsplotgrid)
plotgridBTpvalues_sq<-matrix(nrow=NumPstepsplotgrid, ncol=NumPstepsplotgrid)

plotgridrows<-NumPstepsplotgrid*NumPstepsplotgrid
plotgridP1threshold<-matrix(nrow=plotgridrows, ncol=1)
plotgridP2threshold<-matrix(nrow=plotgridrows, ncol=1)
plotgridBTcountP1P2<-matrix(nrow=plotgridrows, ncol=1)
plotgridBTcountP1<-matrix(nrow=plotgridrows, ncol=1)
plotgridBTcountP2<-matrix(nrow=plotgridrows, ncol=1)
plotgridBTobsProps<-matrix(nrow=plotgridrows, ncol=1)
plotgridBTexpProps<-matrix(nrow=plotgridrows, ncol=1)
plotgridBTobsPropOverExpProps<-matrix(nrow=plotgridrows, ncol=1)
plotgridBTpvalues<-matrix(nrow=plotgridrows, ncol=1)
plotgridFTminusminus<-matrix(nrow=plotgridrows, ncol=1)
plotgridFTplusminus<-matrix(nrow=plotgridrows, ncol=1)
plotgridFTminusplus<-matrix(nrow=plotgridrows, ncol=1)
plotgridFTplusplus<-matrix(nrow=plotgridrows, ncol=1)
plotgridFToddsRatios<-matrix(nrow=plotgridrows, ncol=1)
plotgridFTpvalues<-matrix(nrow=plotgridrows, ncol=1)


plotgridrow<-0
for(j in 1:NumPstepsplotgrid) 
{
  for(k in 1:NumPstepsplotgrid) 
  {
    plotgridrow<-plotgridrow + 1
    plotgridP1threshold[plotgridrow]<-signif(Pstepsplotgrid[j], digits=3)
    plotgridP2threshold[plotgridrow]<-signif(Pstepsplotgrid[k], digits=3)
  }
}

plotgridrow<-0
for(j in 1:NumPstepsplotgrid) 
{
  dataP1plotgrid<-subset(data1.0P1, P1 <= Pstepsplotgrid[j]) 
  for(k in 1:NumPstepsplotgrid) 
  {
    dataP2plotgrid<-subset(data1.0P1, P2 <= Pstepsplotgrid[k]) 
    dataP1P2plotgrid<-subset(dataP1plotgrid, P2 <= Pstepsplotgrid[k]) 

    plotgridrow<-plotgridrow + 1
    plotgridBTcountP1[plotgridrow]<-nrow(dataP1plotgrid)
    plotgridBTcountP2[plotgridrow]<-nrow(dataP2plotgrid)
    plotgridBTcountP1P2[plotgridrow]<-nrow(dataP1P2plotgrid)

    dataP1P2plotgrid_BT<-binom.test(plotgridBTcountP1P2[plotgridrow],plotgridBTcountP1[plotgridrow], alternative ="two.sided", p = plotgridBTcountP2[plotgridrow]/totalSNPs)

    FTtableplotgrid_tmp<-table(dataP1P2plotgrid[c("EFF1","EFF2")])
    FTtableplotgrid<-( FTtableplotgrid_tmp + rotate_matrix_180(FTtableplotgrid_tmp) )/2

    dataP1P2plotgrid_FT<-fisher.test(FTtableplotgrid, alternative ="two.sided")

    plotgridFTors_sq[j,k]<-dataP1P2plotgrid_FT$estimate
    plotgridFTpvalues_sq[j,k]<-dataP1P2plotgrid_FT$p.value
    
    plotgridBTobsProps[plotgridrow]<-round((dataP1P2plotgrid_BT[[5]]), digits=4)
    plotgridBTexpProps[plotgridrow]<-round((dataP1P2plotgrid_BT[[6]]), digits=4)
    plotgridBTobsPropOverExpProps[plotgridrow]<-signif((dataP1P2plotgrid_BT[[5]])/(dataP1P2plotgrid_BT[[6]]), digits=4)
    plotgridBTpvalues[plotgridrow]<-signif(dataP1P2plotgrid_BT[[3]], digits=4)

    plotgridBTratioOEs_sq[j,k]<-(dataP1P2plotgrid_BT[[5]])/(dataP1P2plotgrid_BT[[6]])
    plotgridBTpvalues_sq[j,k]<-dataP1P2plotgrid_BT$p.value

    plotgridFTminusminus[plotgridrow]<-FTtableplotgrid[1]
    plotgridFTplusminus[plotgridrow]<-FTtableplotgrid[2]
    plotgridFTminusplus[plotgridrow]<-FTtableplotgrid[3]    
    plotgridFTplusplus[plotgridrow]<-FTtableplotgrid[4]
    plotgridFToddsRatios[plotgridrow]<-signif(dataP1P2plotgrid_FT[[3]][1], digits=4)
    plotgridFTpvalues[plotgridrow]<-signif(dataP1P2plotgrid_FT[[1]], digits=4)
  }
}

plotgridBTobsProps<-formatC(plotgridBTobsProps, format="f", digits=3) 
plotgridBTobsPropOverExpProps<-format(plotgridBTobsPropOverExpProps, format="f", digits=3) 
plotgridBTpvalues<-format(plotgridBTpvalues, format="f", digits=3, scientific = TRUE) 
plotgridFToddsRatios<-format(plotgridFToddsRatios, format="f", digits=3) 
plotgridFTpvalues<-format(plotgridFTpvalues, format="f", digits=3, scientific = TRUE) 

plotgriddata.table<-cbind(plotgridP1threshold,plotgridP2threshold,plotgridBTcountP1,plotgridBTcountP2,plotgridBTcountP1P2,plotgridBTobsProps,plotgridBTexpProps,plotgridBTobsPropOverExpProps,plotgridBTpvalues,plotgridFTminusminus,plotgridFTplusminus,plotgridFTminusplus,plotgridFTplusplus,plotgridFToddsRatios,plotgridFTpvalues)
colnames(plotgriddata.table)<-c("P1", "P2", "P1snp", "P2snp", "P1P2snp", "PropO", "PropE", "RatioOE", "BtestPval", "--", "+-", "-+", "++", "FtestOR", "FtestPval")


write.table(plotgriddata.table, file="heatmapdata.txt", quote = FALSE, sep = "\t", row.names = FALSE, col.names = TRUE)

##############################################################################################################################

## Calculate the number of OBSERVED Binomial Test BTratioOEs with BTratioOE >= 1 and P <= 0.05:

plotgridBTratioOEs_sq_array<-c(plotgridBTratioOEs_sq)
plotgridBTpvalues_sq_array<-c(plotgridBTpvalues_sq)

# Create an array with values of "1" if plotgridBTpvalues_sq_array <=0.05, and values of "-1" plotgridBTpvalues_sq_array >0.05:
f1 <- function(x) { if(x <= 0.05) {return(1)} else {return(-1)} }
plotgridBTpvalues_sq_array_0.05pos<-apply(as.matrix(plotgridBTpvalues_sq_array), c(1,2), f1)

# Multiply the plotgridBTratioOEs by "1" if P<=0.05 or "-1" if P>0.05:
plotgridBTratioOEs_sq_array_0.05pos<-plotgridBTpvalues_sq_array_0.05pos*plotgridBTratioOEs_sq_array

# Identify plotgridBTratioOEs >=1 and P<=0.05:
f2 <- function(x) { if(x >= 1.0) {return(1)} else {return(0)} } 
plotgridBTratioOEs_sq_array_0.05pos_1plus<-apply(as.matrix(plotgridBTratioOEs_sq_array_0.05pos), c(1,2), f2)

# Calculate the number of plotgridBTratioOEs >=1 and P<=0.05:
#plotgridBTratioOEs_sq_array_0.05pos_1plus_count<-apply(as.matrix(plotgridBTratioOEs_sq_array_0.05pos_1plus), 2, sum)
plotgridBTratioOEs_sq_array_0.05pos_1plus_count<-sum(plotgridBTratioOEs_sq_array_0.05pos_1plus)
plotgridBTratioOEs_sq_array_0.05pos_1plus_count

# Create an array with values of "1" if plotgridBTpvalues_sq_array <=0.1, and values of "-1" plotgridBTpvalues_sq_array >0.1:
f1 <- function(x) { if(x <= 0.1) {return(1)} else {return(-1)} }
plotgridBTpvalues_sq_array_0.1pos<-apply(as.matrix(plotgridBTpvalues_sq_array), c(1,2), f1)

# Multiply the plotgridBTratioOEs by "1" if P<=0.1 or "-1" if P>0.1:
plotgridBTratioOEs_sq_array_0.1pos<-plotgridBTpvalues_sq_array_0.1pos*plotgridBTratioOEs_sq_array

# Identify plotgridBTratioOEs >=1 and P<=0.1:
f2 <- function(x) { if(x >= 1.0) {return(1)} else {return(0)} } 
plotgridBTratioOEs_sq_array_0.1pos_1plus<-apply(as.matrix(plotgridBTratioOEs_sq_array_0.1pos), c(1,2), f2)

# Calculate the number of plotgridBTratioOEs >=1 and P<=0.1:
#plotgridBTratioOEs_sq_array_0.1pos_1plus_count<-apply(as.matrix(plotgridBTratioOEs_sq_array_0.1pos_1plus), 2, sum)
plotgridBTratioOEs_sq_array_0.1pos_1plus_count<-sum(plotgridBTratioOEs_sq_array_0.1pos_1plus)
plotgridBTratioOEs_sq_array_0.1pos_1plus_count

# Identify plotgridBTratioOEs >=1:
f3 <- function(x) { if(x >= 1.0) {return(1)} else {return(NA)} } 
plotgridBTratioOEs_sq_array_1plus<-apply(as.matrix(plotgridBTratioOEs_sq_array), c(1,2), f3)

# Multiply the plotgridBTpvalues by "1" if plotgridBTratioOEs >=1 or convert to "NA" if plotgridBTratioOEs <1:
plotgridBTpvalues_sq_array_pos<-plotgridBTpvalues_sq_array*plotgridBTratioOEs_sq_array_1plus

# Find the most significant pleiotropy p-value:
min_plotgridBTpvalues_sq_array_pos<-min(plotgridBTpvalues_sq_array_pos, na.rm=TRUE)


## Calculate the number of OBSERVED Fisher's Test ORs with OR >= 1 and P <= 0.05:

plotgridFTors_sq_array<-c(plotgridFTors_sq)
plotgridFTpvalues_sq_array<-c(plotgridFTpvalues_sq)

# Create an array with values of "1" if plotgridFTpvalues_sq_array <=0.05, and values of "-1" plotgridFTpvalues_sq_array >0.05:
f1 <- function(x) { if(x <= 0.05) {return(1)} else {return(-1)} }
plotgridFTpvalues_sq_array_0.05pos<-apply(as.matrix(plotgridFTpvalues_sq_array), c(1,2), f1)

# Multiply the ORs by "1" if P<=0.05 or "-1" if P>0.05:
plotgridFTors_sq_array_0.05pos<-plotgridFTpvalues_sq_array_0.05pos*plotgridFTors_sq_array

# Identify plotgridFTors >=1 and P<=0.05:
f2 <- function(x) { if(x >= 1.0) {return(1)} else {return(0)} } 
plotgridFTors_sq_array_0.05pos_1plus<-apply(as.matrix(plotgridFTors_sq_array_0.05pos), c(1,2), f2)

# Calculate the number of plotgridFTors >=1 and P<=0.05:
#plotgridFTors_sq_array_0.05pos_1plus_count<-apply(as.matrix(plotgridFTors_sq_array_0.05pos_1plus), 2, sum)
plotgridFTors_sq_array_0.05pos_1plus_count<-sum(plotgridFTors_sq_array_0.05pos_1plus)
plotgridFTors_sq_array_0.05pos_1plus_count

# Create an array with values of "1" if plotgridFTpvalues_sq_array <=0.1, and values of "-1" plotgridFTpvalues_sq_array >0.1:
f1 <- function(x) { if(x <= 0.1) {return(1)} else {return(-1)} }
plotgridFTpvalues_sq_array_0.1pos<-apply(as.matrix(plotgridFTpvalues_sq_array), c(1,2), f1)

# Multiply the ORs by "1" if P<=0.1 or "-1" if P>0.1:
plotgridFTors_sq_array_0.1pos<-plotgridFTpvalues_sq_array_0.1pos*plotgridFTors_sq_array

# Identify plotgridFTors >=1 and P<=0.1:
f2 <- function(x) { if(x >= 1.0) {return(1)} else {return(0)} } 
plotgridFTors_sq_array_0.1pos_1plus<-apply(as.matrix(plotgridFTors_sq_array_0.1pos), c(1,2), f2)

# Calculate the number of plotgridFTors >=1 and P<=0.1:
#plotgridFTors_sq_array_0.1pos_1plus_count<-apply(as.matrix(plotgridFTors_sq_array_0.1pos_1plus), 2, sum)
plotgridFTors_sq_array_0.1pos_1plus_count<-sum(plotgridFTors_sq_array_0.1pos_1plus)
plotgridFTors_sq_array_0.1pos_1plus_count

# Identify plotgridFTors >=1:
f3 <- function(x) { if(x >= 1.0) {return(1)} else {return(NA)} } 
plotgridFTors_sq_array_1plus<-apply(as.matrix(plotgridFTors_sq_array), c(1,2), f3)

# Multiply the plotgridFTpvalues by "1" if plotgridFTors >=1 or convert to "NA" if plotgridFTors <1:
plotgridFTpvalues_sq_array_pos<-plotgridFTpvalues_sq_array*plotgridFTors_sq_array_1plus

# Find the most significant concordant effects p-value:
min_plotgridFTpvalues_sq_array_pos<-min(plotgridFTpvalues_sq_array_pos, na.rm=TRUE)


## Perform permutations to calculate empirical p-value for the observed number of Fisher's Test ORs and BTratioOEs >= 1 and P <= 0.05 or P <= 0.1:
## Note: the permuted heatmap p-values are only as accurate as the number of replicates, for example:                       ##
##        6 /  101 = 0.059 ; 95%CI = 0.02750813 - 0.12359110                                                                ##
##       51 / 1001 = 0.051 ; 95%CI = 0.03896177 - 0.06636973                                                                ##
##       36 / 1001 = 0.036 ; 95%CI = 0.02608937 - 0.04938667                                                                ##
##       Hence, 1000 permutations are sufficient to indicate pointwise significance                                         ##
##       and whether more permutations are desired to give a 95%CI which does not include 0.05.                             ##
##                                                                                                                          ##
##       10000 permutations are preferable, but would unnecessarily take too long (if there is no trend):                   ##
##       501/10001 = 0.050 ; 95%CI = 0.04598980 - 0.05454568                                                                ##
##       461/10001 = 0.046 ; 95%CI = 0.04215709 - 0.05038225                                                                ##


reps<-1000
permutedFTors_0.05pos_1plus_counts<-matrix(nrow=1, ncol=reps)
permutedBTratioOEs_0.05pos_1plus_counts<-matrix(nrow=1, ncol=reps)
permutedFTors_0.1pos_1plus_counts<-matrix(nrow=1, ncol=reps)
permutedBTratioOEs_0.1pos_1plus_counts<-matrix(nrow=1, ncol=reps)
permutedFTors_minP_1plus_counts<-matrix(nrow=1, ncol=reps)
permutedBTratioOEs_minP_1plus_counts<-matrix(nrow=1, ncol=reps)

#BTratioOEs_1plus0.05_heatmap_input
#FTors_1plus0.05_heatmap_input

for(i in 1:reps) 
{
  BTcount_0.05pos_1plus<-0
  FTcount_0.05pos_1plus<-0
  BTcount_0.1pos_1plus<-0  
  FTcount_0.1pos_1plus<-0  
  BTcount_minP_1plus<-0
  FTcount_minP_1plus<-0
  df<-data1.0P1[c("P1","EFF1")]
  data1.0P1rep<-cbind(df[sample(nrow(df),),],data1.0P1[c("P2","EFF2")])

  for(j in 1:NumPstepsplotgrid) 
  {
    dataP1rep<-subset(data1.0P1rep, P1 <= Pstepsplotgrid[j]) 
    for(k in 1:NumPstepsplotgrid) 
    {
      dataP2rep<-subset(data1.0P1rep, P2 <= Pstepsplotgrid[k]) 
      dataP1P2rep<-subset(dataP1rep, P2 <= Pstepsplotgrid[k]) 
      BTcountP1rep<-nrow(dataP1rep)
      BTcountP2rep<-nrow(dataP2rep)
      BTcountP1P2rep<-nrow(dataP1P2rep)
      dataP1P2rep_BT<-binom.test(BTcountP1P2rep,BTcountP1rep, alternative ="two.sided", p = BTcountP2rep/totalSNPs)
      BTratioOErep<-dataP1P2rep_BT[[5]]/dataP1P2rep_BT[[6]]
      if(dataP1P2rep_BT$p.value <= 0.05 & BTratioOErep >= 1) { BTcount_0.05pos_1plus<-BTcount_0.05pos_1plus + 1 }
      if(dataP1P2rep_BT$p.value <= 0.1 & BTratioOErep >= 1) { BTcount_0.1pos_1plus<-BTcount_0.1pos_1plus + 1 }
      if(dataP1P2rep_BT$p.value <= min_plotgridBTpvalues_sq_array_pos & BTratioOErep >= 1) { BTcount_minP_1plus<-BTcount_minP_1plus + 1 }
      FTtablerep_tmp<-table(dataP1P2rep[c("EFF1","EFF2")])
      FTtablerep<-( FTtablerep_tmp + rotate_matrix_180(FTtablerep_tmp) )/2
      FTrep<-fisher.test(FTtablerep, alternative ="two.sided")
      if(FTrep$p.value <= 0.05 & FTrep$estimate >= 1) { FTcount_0.05pos_1plus<-FTcount_0.05pos_1plus + 1 }
      if(FTrep$p.value <= 0.1 & FTrep$estimate >= 1) { FTcount_0.1pos_1plus<-FTcount_0.1pos_1plus + 1 }
      if(FTrep$p.value <= min_plotgridFTpvalues_sq_array_pos & FTrep$estimate >= 1) { FTcount_minP_1plus<-FTcount_minP_1plus + 1 }
    }
  }
  permutedBTratioOEs_0.05pos_1plus_counts[,i]<-BTcount_0.05pos_1plus
  permutedFTors_0.05pos_1plus_counts[,i]<-FTcount_0.05pos_1plus
  permutedBTratioOEs_0.1pos_1plus_counts[,i]<-BTcount_0.1pos_1plus
  permutedFTors_0.1pos_1plus_counts[,i]<-FTcount_0.1pos_1plus
  permutedBTratioOEs_minP_1plus_counts[,i]<-BTcount_minP_1plus
  permutedFTors_minP_1plus_counts[,i]<-FTcount_minP_1plus
}

permutedBTratioOEs_0.05pos_1plus_countRep<-length(permutedBTratioOEs_0.05pos_1plus_counts[permutedBTratioOEs_0.05pos_1plus_counts >= plotgridBTratioOEs_sq_array_0.05pos_1plus_count])
permutedFTors_0.05pos_1plus_countRep<-length(permutedFTors_0.05pos_1plus_counts[permutedFTors_0.05pos_1plus_counts >= plotgridFTors_sq_array_0.05pos_1plus_count])
permutedBTratioOEs_0.1pos_1plus_countRep<-length(permutedBTratioOEs_0.1pos_1plus_counts[permutedBTratioOEs_0.1pos_1plus_counts >= plotgridBTratioOEs_sq_array_0.1pos_1plus_count])
permutedFTors_0.1pos_1plus_countRep<-length(permutedFTors_0.1pos_1plus_counts[permutedFTors_0.1pos_1plus_counts >= plotgridFTors_sq_array_0.1pos_1plus_count])
permutedBTratioOEs_minP_1plus_countRep<-length(permutedBTratioOEs_minP_1plus_counts[permutedBTratioOEs_minP_1plus_counts >= 1])
permutedFTors_minP_1plus_countRep<-length(permutedFTors_minP_1plus_counts[permutedFTors_minP_1plus_counts >= 1])


# Empirical (permuted) p-value for observing >=BTratioOEs_1plus_count including observed data:
#(permutedBTratioOEs_0.05pos_1plus_countRep+1)
#(reps+1)
#(permutedBTratioOEs_0.05pos_1plus_countRep+1)/(reps+1)

# Empirical (permuted) p-value for observing >=FTors_1plus_count including observed data:
#(permutedFTors_0.05pos_1plus_countRep+1)
#(reps+1)
#(permutedFTors_0.05pos_1plus_countRep+1)/(reps+1)

##############################################################################################################################


# Extract and sort dataset2 p-values from smallest to largest:
p2<-sort(data1.0P1$P2)

# Creat dummy title:
plot.title<-"Dataset2 p-values before and after conditioning on dataset1 p-values"

# Determine total number of p-values:
n <- length(p2)

# Specify alpha for confidence envelope (e.g., alpha = 0.05 will give the expected 95% probability interval for ordered P-values):
alpha <- 0.05

# For the null, make empty array 'successes' of length n:
null_k <- c(1:n)

# Generate expected distribution (under the null):
expect <- (null_k)/n

# For the observed, make an array of 'successes' of length n (for the observed p-values):
observed_k <- p2*n

# Determine maximum values for each axis:
biggest <- (max(-log10(p2),-log10(expect)))

# 'source' a 'local' version of the "binom.confint" function to calculate the Wilson score confidence intervals:
binom.confintWILSON<-function (x, n, conf.level = 0.95, methods = "all", ...) 
{
    if ((length(x) != length(n))) {
        m <- cbind(x = x, n = n)
        x <- m[, "x"]
        n <- m[, "n"]
    }
    res <- NULL
    binom.methods <- c("wilson", "all")
    method <- pmatch(methods, binom.methods)
    if (all(is.na(method))) {
        methods <- paste(paste("\"", methods, "\"", sep = ""), 
            collapse = ", ")
        stop("method(s) ", methods, "\" not matched")
    }
    if (any(is.na(method))) {
        warning("method(s) ", methods[is.na(method)], " not matched")
        method <- methods[!is.na(method)]
    }
    method <- binom.methods[method]
    out <- x > n | x < 0
    if (any(out)) {
        warning("observations with more successes than trials detected and removed")
        x <- x[!out]
        n <- n[!out]
    }
    xn <- data.frame(x = x, n = n)
    all.methods <- any(method == "all")
    p <- x/n
    alpha <- 1 - conf.level
    alpha <- rep(alpha, length = length(p))
    alpha2 <- 0.5 * alpha
    z <- qnorm(1 - alpha2)
    z2 <- z * z
    res <- NULL
    if (any(method == "wilson") || all.methods) {
        p1 <- p + 0.5 * z2/n
        p2 <- z * sqrt((p * (1 - p) + 0.25 * z2/n)/n)
        p3 <- 1 + z2/n
        lcl <- (p1 - p2)/p3
        ucl <- (p1 + p2)/p3
        x1 <- x == 1
        x2 <- x == n - 1
        if (any(x1)) 
            lcl[x1] <- -log(1 - alpha[x1])/n[x1]
        if (any(x2)) 
            ucl[x2] <- 1 + log(1 - alpha[x2])/n[x2]
        res.wilson <- cbind(method = rep("wilson", NROW(x)), 
            xn, mean = p, lower = lcl, upper = ucl)
        res <- if (is.null(res)) 
            res.wilson
        else rbind(res, res.wilson)
    }
    attr(res, "conf.level") <- conf.level
    row.names(res) <- seq(nrow(res))
    res
}

# Function to draw shaded confidence envelope:
shade <- function(x1, y1, x2, y2, color = col.shade) {
n <- length(x2)
polygon(c(x1, x2[n:1]), c(y1, y2[n:1]), border = NA, col = color)
}

# Calculate confidence envelope for the null:
# "Wilson score interval": http://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval
WilsonNullCI<-binom.confintWILSON(x = null_k, n = n, conf.level = 1-alpha, methods = "wilson")
null_lower<-WilsonNullCI$lower
null_upper<-WilsonNullCI$upper

## Extract subset of SNPs from dataset2 with p-values <=0.1 in dataset1 (P1 <= 0.1):
data0.1P1<-subset(data1.0P1, P1 <= 0.1)
p2c0.1P1<-sort(data0.1P1$P2)
nc0.1P1 <- length(p2c0.1P1)
observed_kc0.1P1 <- c(1:nc0.1P1)
expect_c0.1P1 <- (observed_kc0.1P1)/nc0.1P1	# exclude continuity correction

## Extract subset of SNPs from dataset2 with p-values <=0.2 in dataset1 (P1 <= 0.2):
data0.2P1<-subset(data1.0P1, P1 <= 0.2)
p2c0.2P1<-sort(data0.2P1$P2)
nc0.2P1 <- length(p2c0.2P1)
observed_kc0.2P1 <- c(1:nc0.2P1)
expect_c0.2P1 <- (observed_kc0.2P1)/nc0.2P1	# exclude continuity correction

## Extract subset of SNPs from dataset2 with p-values <=0.3 in dataset1 (P1 <= 0.3):
data0.3P1<-subset(data1.0P1, P1 <= 0.3)
p2c0.3P1<-sort(data0.3P1$P2)
nc0.3P1 <- length(p2c0.3P1)
observed_kc0.3P1 <- c(1:nc0.3P1)
expect_c0.3P1 <- (observed_kc0.3P1)/nc0.3P1	# exclude continuity correction

## Extract subset of SNPs from dataset2 with p-values <=0.4 in dataset1 (P1 <= 0.4):
data0.4P1<-subset(data1.0P1, P1 <= 0.4)
p2c0.4P1<-sort(data0.4P1$P2)
nc0.4P1 <- length(p2c0.4P1)
observed_kc0.4P1 <- c(1:nc0.4P1)
expect_c0.4P1 <- (observed_kc0.4P1)/nc0.4P1	# exclude continuity correction

## Extract subset of SNPs from dataset2 with p-values <=0.5 in dataset1 (P1 <= 0.5):
data0.5P1<-subset(data1.0P1, P1 <= 0.5)
p2c0.5P1<-sort(data0.5P1$P2)
nc0.5P1 <- length(p2c0.5P1)
observed_kc0.5P1 <- c(1:nc0.5P1)
expect_c0.5P1 <- (observed_kc0.5P1)/nc0.5P1	# exclude continuity correction

## Extract subset of SNPs from dataset2 with p-values <=0.75 in dataset1 (P1 <= 0.75):
data0.75P1<-subset(data1.0P1, P1 <= 0.75)
p2c0.75P1<-sort(data0.75P1$P2)
nc0.75P1 <- length(p2c0.75P1)
observed_kc0.75P1 <- c(1:nc0.75P1)
expect_c0.75P1 <- (observed_kc0.75P1)/nc0.75P1	# exclude continuity correction


## Q-Q Plot full range

pdf(file="QQplots.pdf", bg = "white")

# Increase left margin to provide space between label and plot border
par(mar=c(5,5,4,2)+0.1)

QQplot.title<-"Q-Q plots for dataset2 p-values (P2) conditioned on dataset1 p-values (P1)"

plot(-log10(expect),-log10(p2), main=QQplot.title, xlim=c(0,biggest),ylim=c(0,biggest),ylab=expression(paste("Observed  ",-log[10],"(P2)")), xlab=expression(paste("Expected  ",-log[10],"(P2)")), type = "n", cex.main = 1.0, cex.lab = 1.0, cex.axis = 1.0)
shade(-log10(expect),-log10(null_lower),-log10(expect),-log10(null_upper), color = "lightgray")

lines(-log10(expect),-log10(p2), lty=1, lwd=3, col="black")
abline(0,1,col="white",lwd=2)

lines(-log10(expect_c0.1P1),-log10(p2c0.1P1), lty=1, lwd=3, col="red")
lines(-log10(expect_c0.2P1),-log10(p2c0.2P1), lty=1, lwd=3, col="orange")
lines(-log10(expect_c0.3P1),-log10(p2c0.3P1), lty=1, lwd=3, col="green4")
lines(-log10(expect_c0.4P1),-log10(p2c0.4P1), lty=1, lwd=3, col="deepskyblue")
lines(-log10(expect_c0.5P1),-log10(p2c0.5P1), lty=1, lwd=3, col="blue")
lines(-log10(expect_c0.75P1),-log10(p2c0.75P1), lty=1, lwd=3, col="purple")

legend("bottomright", inset=.02, c(expression("P1" <= "0.10"),expression("P1" <= "0.20"),expression("P1" <= "0.30"),expression("P1" <= "0.40"),expression("P1" <= "0.50"),expression("P1" <= "0.75"),expression("All SNPs")), col=c("red","orange","green4","deepskyblue","blue","purple","black"), lty=1, lwd=3, horiz=FALSE)

dev.off()


## TDR Plot:

pdf(file="TDRplots.pdf", bg = "white")

# Increase left margin to provide space between label and plot border
par(mar=c(5,5,4,2)+0.1)

TDRplot.title<-"TDR plots for dataset2 p-values (P2) conditioned on dataset1 p-values (P1)"

p2_padjustBH <- p.adjust(p2,method="BH")

plot(-log10(p2), 1-p2_padjustBH, main=TDRplot.title, ylab="TDR", xlab=expression(paste("Observed  ",-log[10],"(P2)")), type="n", cex.main = 1.0, cex.lab = 1.0, cex.axis = 1.0)

p2c0.75P1_padjustBH <- p.adjust(p2c0.75P1,method="BH")
p2c0.5P1_padjustBH <- p.adjust(p2c0.5P1,method="BH")
p2c0.4P1_padjustBH <- p.adjust(p2c0.4P1,method="BH")
p2c0.3P1_padjustBH <- p.adjust(p2c0.3P1,method="BH")
p2c0.2P1_padjustBH <- p.adjust(p2c0.2P1,method="BH")
p2c0.1P1_padjustBH <- p.adjust(p2c0.1P1,method="BH")

lines(-log10(p2), 1-p2_padjustBH, lty=1, lwd=3, col="black")
lines(-log10(p2c0.75P1), 1-p2c0.75P1_padjustBH, lty=1, lwd=3, col="purple")
lines(-log10(p2c0.5P1), 1-p2c0.5P1_padjustBH, lty=1, lwd=3, col="blue")
lines(-log10(p2c0.4P1), 1-p2c0.4P1_padjustBH, lty=1, lwd=3, col="deepskyblue")
lines(-log10(p2c0.3P1), 1-p2c0.3P1_padjustBH, lty=1, lwd=3, col="green4")
lines(-log10(p2c0.2P1), 1-p2c0.2P1_padjustBH, lty=1, lwd=3, col="orange")
lines(-log10(p2c0.1P1), 1-p2c0.1P1_padjustBH, lty=1, lwd=3, col="red")

legend("bottomright", inset=.02, c(expression("P1" <= "0.10"),expression("P1" <= "0.20"),expression("P1" <= "0.30"),expression("P1" <= "0.40"),expression("P1" <= "0.50"),expression("P1" <= "0.75"),expression("All SNPs")), col=c("red","orange","green4","deepskyblue","blue","purple","black"), lty=1, lwd=3, horiz=FALSE)

dev.off()


## Generate FDR (q-values) for dataset2 (P2) p-values and write to file ("dataset2_FDR.txt"):

# Extract additional subset of SNPs from dataset2 conditioned on dataset1 p-values:
data0.9P1<-subset(data1.0P1, P1 <= 0.9)
data0.8P1<-subset(data1.0P1, P1 <= 0.8)
data0.7P1<-subset(data1.0P1, P1 <= 0.7)
data0.6P1<-subset(data1.0P1, P1 <= 0.6)
data0.05P1<-subset(data1.0P1, P1 <= 0.05)
data0.01P1<-subset(data1.0P1, P1 <= 0.01)
dataE_3P1<-subset(data1.0P1, P1 <= 0.001)
dataE_4P1<-subset(data1.0P1, P1 <= 0.0001)
dataE_5P1<-subset(data1.0P1, P1 <= 0.00001)

# Calculate stratified FDRs:
data1.0P1_FDR<-data1.0P1

data1.0P1_FDR$P2fdr<-signif(p.adjust(data1.0P1$P2,method="BH"), digits=4)

data0.9P1$P2fdr0.9P1<-signif(p.adjust(data0.9P1$P2,method="BH"), digits=4)
data0.8P1$P2fdr0.8P1<-signif(p.adjust(data0.8P1$P2,method="BH"), digits=4)
data0.7P1$P2fdr0.7P1<-signif(p.adjust(data0.7P1$P2,method="BH"), digits=4)
data0.6P1$P2fdr0.6P1<-signif(p.adjust(data0.6P1$P2,method="BH"), digits=4)

data0.5P1$P2fdr0.5P1<-signif(p.adjust(data0.5P1$P2,method="BH"), digits=4)
data0.4P1$P2fdr0.4P1<-signif(p.adjust(data0.4P1$P2,method="BH"), digits=4)
data0.3P1$P2fdr0.3P1<-signif(p.adjust(data0.3P1$P2,method="BH"), digits=4)
data0.2P1$P2fdr0.2P1<-signif(p.adjust(data0.2P1$P2,method="BH"), digits=4)
data0.1P1$P2fdr0.1P1<-signif(p.adjust(data0.1P1$P2,method="BH"), digits=4)

data0.05P1$P2fdr0.05P1<-signif(p.adjust(data0.05P1$P2,method="BH"), digits=4)
data0.01P1$P2fdr0.01P1<-signif(p.adjust(data0.01P1$P2,method="BH"), digits=4)
dataE_3P1$P2fdrE_3P1<-signif(p.adjust(dataE_3P1$P2,method="BH"), digits=4)
dataE_4P1$P2fdrE_4P1<-signif(p.adjust(dataE_4P1$P2,method="BH"), digits=4)
dataE_5P1$P2fdrE_5P1<-signif(p.adjust(dataE_5P1$P2,method="BH"), digits=4)

# Merge the FDRs into a single data frame:
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.9P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.8P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.7P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.6P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.5P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.4P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.3P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.2P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.1P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.05P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, data0.01P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, dataE_3P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, dataE_4P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)
data1.0P1_FDR<-merge(data1.0P1_FDR, dataE_5P1[,c(1,10)],by="SNP", all = TRUE, sort = FALSE)


# Trim merged data frame:
data1.0P1_FDR_toWrite<-data1.0P1_FDR[,c(1,2,3,7,8,10:24)]

# Order by P2:
data1.0P1_FDR_toWrite<-data1.0P1_FDR_toWrite[with(data1.0P1_FDR_toWrite, order(P2)), ]

# Format FDR values:
data1.0P1_FDR_toWrite[,6:20]<-format(data1.0P1_FDR_toWrite[,6:20], format="f", digits=3, scientific = TRUE) 


# Paste write.fwf function for portability:

write.fwf.pasted<-function (x, file = "", append = FALSE, quote = FALSE, sep = " ", 
    na = "", rownames = FALSE, colnames = TRUE, rowCol = NULL, 
    justify = "left", formatInfo = FALSE, quoteInfo = TRUE, width = NULL, 
    eol = "\n", qmethod = c("escape", "double"), ...) 
{
    if (!(is.data.frame(x) || is.matrix(x))) 
        stop("'x' must be a data.frame or matrix")
    if (length(na) > 1) 
        stop("only single value can be defined for 'na'")
    if (rownames) {
        x <- cbind(rownames(x), x)
        rowColVal <- ifelse(!is.null(rowCol), rowCol, "row")
        colnames(x)[1] <- rowColVal
    }
    colnamesMy <- colnames(x)
    nRow <- nrow(x)
    nCol <- length(colnamesMy)
    widthNULL <- is.null(width)
    if (!widthNULL && length(width) != nCol) {
        warning("recycling 'width'")
        widthOld <- width
        width <- integer(length = nCol)
        width[] <- widthOld
    }
    retFormat <- data.frame(colname = colnamesMy, nlevels = 0, 
        position = 0, width = 0, digits = 0, exp = 0, stringsAsFactors = FALSE)
    isNum <- sapply(x, is.numeric)
    isNum <- isNum & !(sapply(x, inherits, what = "Date") | sapply(x, 
        inherits, what = "POSIXt"))
    isFac <- sapply(x, is.factor)
    x[, isFac] <- lapply(x[, isFac, drop = FALSE], as.character)
    tmp <- lapply(x, format.info, ...)
    tmp1 <- sapply(tmp, length)
    tmp <- t(as.data.frame(tmp))
    retFormat$width <- tmp[, 1]
    if (any(isNum)) {
        test <- tmp1 > 1
        if (any(test)) {
            retFormat[test, c("digits", "exp")] <- tmp[test, 
                c(2, 3)]
            test2 <- tmp[test, 3] > 0
            if (any(test2)) 
                retFormat[test, ][test2, "exp"] <- retFormat[test, 
                  ][test2, "exp"] + 1
        }
    }
    for (i in 1:nCol) {
        if (widthNULL) {
            tmp <- NULL
        }
        else {
            tmp <- width[i]
        }
        test <- is.na(x[, i])
        x2 <- character(length = nRow)
        x2[!test] <- format(x[!test, i], justify = justify, width = tmp, 
            ...)
        x2[test] <- na
        x[, i] <- x2
        tmp2 <- format.info(x[, i], ...)[1]
        if (tmp2 != retFormat[i, "width"]) {
            retFormat[i, "width"] <- tmp2
            x[, i] <- format(x[, i], justify = ifelse(isNum[i], 
                "right", justify), width = tmp, ...)
        }
        if (nchar(na) < retFormat[i, "width"]) {
            x[test, i] <- format(na, justify = ifelse(isNum[i], 
                "right", justify), width = retFormat[i, "width"], 
                ...)
        }
    }
    if (any(!isNum)) {
        retFormat[!isNum, "nlevels"] <- sapply(x[, !isNum, drop = FALSE], 
            function(z) length(unique(z)))
    }
    if (!widthNULL) {
        test <- retFormat$width > width
        if (any(test)) {
            tmpCol <- paste(colnamesMy[test], collapse = ", ")
            tmpWidth <- paste(width[test], collapse = ", ")
            tmpNeed <- paste(retFormat$width[test], collapse = ", ")
            stop(paste("'width' (", tmpWidth, ") was too small for columns: ", 
                tmpCol, "\n 'width' should be at least (", tmpNeed, 
                ")", sep = ""))
        }
    }
    if (colnames) {
        if (rownames && is.null(rowCol)) 
            colnamesMy <- colnamesMy[-1]
        write.table(t(as.matrix(colnamesMy)), file = file, append = append, 
            quote = quote, sep = sep, eol = eol, na = na, row.names = FALSE, 
            col.names = FALSE, qmethod = qmethod)
    }
    write.table(x = x, file = file, append = (colnames || append), 
        quote = quote, sep = sep, eol = eol, na = na, row.names = FALSE, 
        col.names = FALSE, qmethod = qmethod)
    if (formatInfo) {
        retFormat$position[1] <- ifelse(quote, ifelse(quoteInfo, 
            1, 2), 1)
        if (ifelse(quote, quoteInfo, FALSE)) 
            retFormat$width <- retFormat$width + 2
        N <- nrow(retFormat)
        if (N > 1) {
            for (i in 2:N) {
                retFormat$position[i] <- retFormat$position[i - 
                  1] + retFormat$width[i - 1] + nchar(x = sep, 
                  type = "chars") + ifelse(quote, ifelse(quoteInfo, 
                  0, 1), 0)
            }
        }
        if (rownames && is.null(rowCol)) {
            retFormat <- retFormat[-1, ]
            rownames(retFormat) <- 1:(N - 1)
        }
        return(retFormat)
    }
}


# Set column names to match field width of values:
colnames(data1.0P1_FDR_toWrite)<-c("SNP", "EA", "NEA", "BETA2", "P2", "FDR", "FDR.90P1", "FDR.80P1", "FDR.70P1", "FDR.60P1", "FDR.50P1", "FDR.40P1", "FDR.30P1", "FDR.20P1", "FDR.10P1", "FDR.05P1", "FDR.01P1", "FDRe-3P1", "FDRe-4P1", "FDRe-5P1")

# Place the column names into the dataframe to ensure the formatting of column names and column values are consistent:
# Make vector of column names

col.names<-c("SNP", "EA", "NEA", "BETA2", "P2", "FDR", "FDR.90P1", "FDR.80P1", "FDR.70P1", "FDR.60P1", "FDR.50P1", "FDR.40P1", "FDR.30P1", "FDR.20P1", "FDR.10P1", "FDR.05P1", "FDR.01P1", "FDRe-3P1", "FDRe-4P1", "FDRe-5P1")

# Convert values to strings (otherwise rbin fails for "SNP", EA", and "NEA"):

data1.0P1_FDR_toWrite<-data.frame(lapply(data1.0P1_FDR_toWrite, as.character), stringsAsFactors=FALSE)

# rbind
data1.0P1_FDR_toWrite<-rbind(col.names, data1.0P1_FDR_toWrite)

# Recode "NA" text values as missing
data1.0P1_FDR_toWrite[data1.0P1_FDR_toWrite=="NA"]<-NA

# Remove columns where ALL values are missing (NA):
data1.0P1_FDR_toWrite<-Filter(function(x)!all(is.na(x)), data1.0P1_FDR_toWrite)

# Write out fixed width FDR values for dataset2:
write.fwf.pasted(data1.0P1_FDR_toWrite, file="dataset2_FDR.txt", append=FALSE, quote=FALSE, sep="  ", na="NA", rownames=FALSE, colnames=FALSE, rowCol=NULL, justify="right", formatInfo=FALSE, quoteInfo=TRUE, width=NULL, eol="\n", qmethod="escape")


##############################################################################################################################

## Primary test for pleiotropy and SNP effect concordance

data0.05P1<-subset(data1.0P1, P1 <= 0.05) 
data0.05P2<-subset(data1.0P1, P2 <= 0.05) 
data0.05P10.05P2<-subset(data0.05P1, P2 <= 0.05) 

data0.05P10.05P2_BT<-binom.test(nrow(data0.05P10.05P2),nrow(data0.05P1), alternative ="two.sided", p = nrow(data0.05P2)/nrow(data1.0P1))
ci<-paste(round(data0.05P10.05P2_BT[[4]][1], digits=4),"-",round(data0.05P10.05P2_BT[[4]][2], digits=4), sep="")
data0.05P10.05P2_BTresults<-unname(c(data0.05P10.05P2_BT[[2]], data0.05P10.05P2_BT[[1]], paste(round(data0.05P10.05P2_BT[[5]], digits=4), " (", ci, ")", sep=""), round(data0.05P10.05P2_BT[[6]], digits=4), format(data0.05P10.05P2_BT[[3]], digits=4)))
names(data0.05P10.05P2_BTresults)<-c("  SNPs with P1 <= 0.05 and P2 <= 1.00\t\t:", "  SNPs with P1 <= 0.05 and P2 <= 0.05\t\t:", "  Observed proportion (95%CI)\t\t\t:", "  Expected proportion\t\t\t\t:", "  Exact binomial test p-value (two-sided)\t:")

#outfile <- paste0(outdir, "/", code, ".SECA_results.txt")

outfile <- paste0(code, ".SECA_results.txt")
sink(outfile)

## Write out primary results

cat("\n## SECA: SNP Effect Concordance Analysis - Results ##\n")

Introduction_ToCat<-paste("The total number of independent SNPs overlapping the two datasets = ", format(totalSNPs, digits=1), sep="")
cat("\n")
cat(Introduction_ToCat)
cat("\n")

cat("\n___________________________________________________________________________________________________________________________________________________________________\n\n")
     
cat("\nPrimary test for overlap of associated effects in dataset1 and dataset2 (pleiotropy):\n") 
cat("\nA total of 144 key SNP subsets were examined - generated using twelve p-value thresholds.\n")
cat("That is, {P1,P2} = {0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9 and 1.0}.\n") 
cat("Also see the Binomial test heatmap plot (BTheatmap.pdf) and the raw heatmap data (heatmapdata.txt).\n")

plotgridBTratioOEs_sq_array_0.05pos_1plus_count_ToCat<-paste("The total number of SNP subsets with nominally significant pleiotropy (i.e., Binomial tests with Obs >= Exp and P <= 0.05) = ", format(plotgridBTratioOEs_sq_array_0.05pos_1plus_count, digits=1), sep="")
cat("\n")
cat(plotgridBTratioOEs_sq_array_0.05pos_1plus_count_ToCat)
cat("\n")
permutedBTratioOEs_0.05pos_1plus_countRep_ToCat<-paste("Out of ", format(reps, digits=1), " replicates, ", format(permutedBTratioOEs_0.05pos_1plus_countRep, digits=1), " produced ", format(plotgridBTratioOEs_sq_array_0.05pos_1plus_count, digits=1), " or more subsets with nominally significant pleiotropy.", sep="")
cat("\n")
cat(permutedBTratioOEs_0.05pos_1plus_countRep_ToCat)
cat("\n")

BTempP_0.05pos_1plus<-(permutedBTratioOEs_0.05pos_1plus_countRep+1)/(reps+1)
BTempP_0.05pos_1plus95CI_L<-binom.confintWILSON(x = (permutedBTratioOEs_0.05pos_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$lower
BTempP_0.05pos_1plus95CI_U<-binom.confintWILSON(x = (permutedBTratioOEs_0.05pos_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$upper

permutedBTratioOEs_0.05pos_1plus_countRep_empP_ToCat<-paste("The empirical (permuted) p-value for observing ", format(plotgridBTratioOEs_sq_array_0.05pos_1plus_count, digits=1), " or more SNP subsets with nominally significant pleiotropy = ", format(BTempP_0.05pos_1plus, digits=3), " (95% CI: ", format(BTempP_0.05pos_1plus95CI_L, digits=3), "-", format(BTempP_0.05pos_1plus95CI_U, digits=3), ")", sep="")
cat("\n")
cat(permutedBTratioOEs_0.05pos_1plus_countRep_empP_ToCat)
cat("\n")

if(BTempP_0.05pos_1plus <= 0.05) 
{ 
  cat("\n   * The number of SNP subsets with nominally significant pleiotropy is significantly MORE than expected by chance.") 
  cat("\n   * Thus indicating significant pleiotropy between the two datasets.\n")
}
if(BTempP_0.05pos_1plus > 0.05) 
{
  cat("\n   * The number of SNP subsets with nominally significant pleiotropy is NOT significantly more than expected by chance.") 
  cat("\n   * Thus indicating no significant pleiotropy between the two datasets.\n")
}

BTempP_minP_1plus<-(permutedBTratioOEs_minP_1plus_countRep+1)/(reps+1)
BTempP_minP_1plus95CI_L<-binom.confintWILSON(x = (permutedBTratioOEs_minP_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$lower
BTempP_minP_1plus95CI_U<-binom.confintWILSON(x = (permutedBTratioOEs_minP_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$upper

permutedBTratioOEs_minP_1plus_countRep_empP_ToCat<-paste("The empirical (permuted) p-value for the smallest observed pleiotropy p-value (", format(min_plotgridBTpvalues_sq_array_pos, digits=3), ") = ", format(BTempP_minP_1plus, digits=3), " (95% CI: ", format(BTempP_minP_1plus95CI_L, digits=3), "-", format(BTempP_minP_1plus95CI_U, digits=3), ")", sep="")
cat("\n")
cat(permutedBTratioOEs_minP_1plus_countRep_empP_ToCat)
cat("\n")


cat("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n")
     
plotgridBTratioOEs_sq_array_0.1pos_1plus_count_ToCat<-paste("The total number of SNP subsets with marginally significant pleiotropy (i.e., Binomial tests with Obs >= Exp and P <= 0.1) = ", format(plotgridBTratioOEs_sq_array_0.1pos_1plus_count, digits=1), sep="")
cat("\n")
cat(plotgridBTratioOEs_sq_array_0.1pos_1plus_count_ToCat)
cat("\n")
permutedBTratioOEs_0.1pos_1plus_countRep_ToCat<-paste("Out of ", format(reps, digits=1), " replicates, ", format(permutedBTratioOEs_0.1pos_1plus_countRep, digits=1), " produced ", format(plotgridBTratioOEs_sq_array_0.1pos_1plus_count, digits=1), " or more subsets with marginally significant pleiotropy.", sep="")
cat("\n")
cat(permutedBTratioOEs_0.1pos_1plus_countRep_ToCat)
cat("\n")

BTempP_0.1pos_1plus<-(permutedBTratioOEs_0.1pos_1plus_countRep+1)/(reps+1)
BTempP_0.1pos_1plus95CI_L<-binom.confintWILSON(x = (permutedBTratioOEs_0.1pos_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$lower
BTempP_0.1pos_1plus95CI_U<-binom.confintWILSON(x = (permutedBTratioOEs_0.1pos_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$upper

permutedBTratioOEs_0.1pos_1plus_countRep_empP_ToCat<-paste("The empirical (permuted) p-value for observing ", format(plotgridBTratioOEs_sq_array_0.1pos_1plus_count, digits=1), " or more SNP subsets with marginally significant pleiotropy = ", format(BTempP_0.1pos_1plus, digits=3), " (95% CI: ", format(BTempP_0.1pos_1plus95CI_L, digits=3), "-", format(BTempP_0.1pos_1plus95CI_U, digits=3), ")", sep="")
cat("\n")
cat(permutedBTratioOEs_0.1pos_1plus_countRep_empP_ToCat)
cat("\n")

if(BTempP_0.1pos_1plus <= 0.05) 
{ 
  cat("\n   * The number of SNP subsets with marginally significant pleiotropy is significantly MORE than expected by chance.") 
  cat("\n   * Thus indicating weak but significant pleiotropy between the two datasets.\n")
}
if(BTempP_0.1pos_1plus > 0.05) 
{
  cat("\n   * The number of SNP subsets with marginally significant pleiotropy is NOT significantly more than expected by chance.") 
  cat("\n   * Thus indicating no significant pleiotropy between the two datasets.\n")
}


cat("\n___________________________________________________________________________________________________________________________________________________________________\n\n")
       

cat("\nPrimary test for concordant SNP effects (directions) between dataset1 and dataset2:\n") 
cat("\nA total of 144 key SNP subsets were examined - generated using twelve p-value thresholds.\n")
cat("That is, {P1,P2} = {0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9 and 1.0}.\n") 
cat("Also see the Fisher's Test heatmap plot (FTheatmap.pdf) and the raw heatmap data (heatmapdata.txt).\n")

plotgridFTors_sq_array_0.05pos_1plus_count_ToCat<-paste("The total number of SNP subsets with nominally significant concordant effects (i.e., Fisher's Tests with OR >= 1 and P <= 0.05) = ", format(plotgridFTors_sq_array_0.05pos_1plus_count, digits=1), sep="")
cat("\n")
cat(plotgridFTors_sq_array_0.05pos_1plus_count_ToCat)
cat("\n")
permutedFTors_0.05pos_1plus_countRep_ToCat<-paste("Out of ", format(reps, digits=1), " replicates, ", format(permutedFTors_0.05pos_1plus_countRep, digits=1), " produced ", format(plotgridFTors_sq_array_0.05pos_1plus_count, digits=1), " or more subsets with nominally significant concordant effects.", sep="")
cat("\n")
cat(permutedFTors_0.05pos_1plus_countRep_ToCat)
cat("\n")

FTempP_0.05pos_1plus<-(permutedFTors_0.05pos_1plus_countRep+1)/(reps+1)
FTempP_0.05pos_1plus95CI_L<-binom.confintWILSON(x = (permutedFTors_0.05pos_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$lower
FTempP_0.05pos_1plus95CI_U<-binom.confintWILSON(x = (permutedFTors_0.05pos_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$upper

permutedFTors_0.05pos_1plus_countRep_empP_ToCat<-paste("The empirical (permuted) p-value for observing ", format(plotgridFTors_sq_array_0.05pos_1plus_count, digits=1), " or more SNP subsets with nominally significant concordant effects = ", format(FTempP_0.05pos_1plus, digits=3), " (95% CI: ", format(FTempP_0.05pos_1plus95CI_L, digits=3), "-", format(FTempP_0.05pos_1plus95CI_U, digits=3), ")", sep="")
cat("\n")
cat(permutedFTors_0.05pos_1plus_countRep_empP_ToCat)
cat("\n")

if(FTempP_0.05pos_1plus <= 0.05) 
{ 
  cat("\n   * The number of SNP subsets with nominally significant concordant effects is significantly MORE than expected by chance.") 
  cat("\n   * Thus indicating significant concordance of genetic risk between the two datasets.\n")
}
if(FTempP_0.05pos_1plus > 0.05) 
{
  cat("\n   * The number of SNP subsets with nominally significant concordant effects is NOT significantly more than expected by chance.") 
  cat("\n   * Thus indicating no significant concordance of genetic risk between the two datasets.\n")
}

FTempP_minP_1plus<-(permutedFTors_minP_1plus_countRep+1)/(reps+1)
FTempP_minP_1plus95CI_L<-binom.confintWILSON(x = (permutedFTors_minP_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$lower
FTempP_minP_1plus95CI_U<-binom.confintWILSON(x = (permutedFTors_minP_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$upper

permutedFTors_minP_1plus_countRep_empP_ToCat<-paste("The empirical (permuted) p-value for the smallest observed concordant effects p-value (", format(min_plotgridFTpvalues_sq_array_pos, digits=3), ") = ", format(FTempP_minP_1plus, digits=3), " (95% CI: ", format(FTempP_minP_1plus95CI_L, digits=3), "-", format(FTempP_minP_1plus95CI_U, digits=3), ")", sep="")
cat("\n")
cat(permutedFTors_minP_1plus_countRep_empP_ToCat)
cat("\n")


cat("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n")

plotgridFTors_sq_array_0.1pos_1plus_count_ToCat<-paste("The total number of SNP subsets with marginally significant concordant effects (i.e., Fisher's Tests with OR >= 1 and P <= 0.1) = ", format(plotgridFTors_sq_array_0.1pos_1plus_count, digits=1), sep="")
cat("\n")
cat(plotgridFTors_sq_array_0.1pos_1plus_count_ToCat)
cat("\n")
permutedFTors_0.1pos_1plus_countRep_ToCat<-paste("Out of ", format(reps, digits=1), " replicates, ", format(permutedFTors_0.1pos_1plus_countRep, digits=1), " produced ", format(plotgridFTors_sq_array_0.1pos_1plus_count, digits=1), " or more subsets with marginally significant concordant effects.", sep="")
cat("\n")
cat(permutedFTors_0.1pos_1plus_countRep_ToCat)
cat("\n")

FTempP_0.1pos_1plus<-(permutedFTors_0.1pos_1plus_countRep+1)/(reps+1)
FTempP_0.1pos_1plus95CI_L<-binom.confintWILSON(x = (permutedFTors_0.1pos_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$lower
FTempP_0.1pos_1plus95CI_U<-binom.confintWILSON(x = (permutedFTors_0.1pos_1plus_countRep+1), n = (reps+1), conf.level = 0.95, methods = "wilson")$upper

permutedFTors_0.1pos_1plus_countRep_empP_ToCat<-paste("The empirical (permuted) p-value for observing ", format(plotgridFTors_sq_array_0.1pos_1plus_count, digits=1), " or more SNP subsets with marginally significant concordant effects = ", format(FTempP_0.1pos_1plus, digits=3), " (95% CI: ", format(FTempP_0.1pos_1plus95CI_L, digits=3), "-", format(FTempP_0.1pos_1plus95CI_U, digits=3), ")", sep="")
cat("\n")
cat(permutedFTors_0.1pos_1plus_countRep_empP_ToCat)
cat("\n")

if(FTempP_0.1pos_1plus <= 0.05) 
{ 
  cat("\n   * The number of SNP subsets with marginally significant concordant effects is significantly MORE than expected by chance.") 
  cat("\n   * Thus indicating significant concordance of genetic risk between the two datasets.\n")
}
if(FTempP_0.1pos_1plus > 0.05) 
{
  cat("\n   * The number of SNP subsets with marginally significant concordant effects is NOT significantly more than expected by chance.") 
  cat("\n   * Thus indicating no significant concordance of genetic risk between the two datasets.\n")
}


cat("\n___________________________________________________________________________________________________________________________________________________________________\n\n")


cat("\nTests for genetic overlap between dataset1 SNPs and dataset2 SNPs with P <= 0.05\n") 
cat("\nSNPs with P1 <= 0.05 and P2 <= 0.05\n") 

write.table(data0.05P10.05P2_BTresults, quote = FALSE, col.names = "\nTest for overlap of associated effects in dataset1 and dataset2 (pleiotropy):\n")
if(unname(data0.05P10.05P2_BT[[1]]) == 0) 
{ 
  cat("\n   * None of the SNPs in dataset1 (P1 <= 0.05) were associated in dataset2 (P1 <= 0.05).") 
  cat("\n   * If significant, this is strange and difficult to explain...\n") 
}
if(unname(data0.05P10.05P2_BT[[1]]) > 0) 
{ 
  if(data0.05P10.05P2_BT[[5]] > data0.05P10.05P2_BT[[6]]) 
  { 
    cat("\n   * The number of SNPs associated in both datasets was MORE than expected.") 
    cat("\n   * If significant, this could indicate the presence of pleiotropy")
    cat("\n     (i.e., some genetic variants influence both traits).\n") 
  }
  if(data0.05P10.05P2_BT[[5]] < data0.05P10.05P2_BT[[6]]) 
  { 
    cat("\n   * The number of SNPs associated in both datasets was LESS than expected.") 
    cat("\n   * If significant, this is strange and difficult to explain...\n") 
  }

  cat("\n\nCross tabulation of effect direction in dataset1 (EFF1) versus dataset2 (EFF2):\n\n")

#  write.ftable(ftable(data0.05P10.05P2[c("EFF1","EFF2")]), quote = FALSE)
#  cat("\n\n")

#  data0.05P10.05P2_FT<-fisher.test(table(data0.05P10.05P2[c("EFF1","EFF2")]), alternative ="two.sided")

  FTftable0.05P10.05P2_tmp<-ftable(data0.05P10.05P2[c("EFF1","EFF2")])
  FTftable0.05P10.05P2<-( FTftable0.05P10.05P2_tmp + rotate_matrix_180(FTftable0.05P10.05P2_tmp) )/2
  write.ftable(FTftable0.05P10.05P2, quote = FALSE)
  cat("\n\n")

  FTtable0.05P10.05P2_tmp<-table(data0.05P10.05P2[c("EFF1","EFF2")])
  FTtable0.05P10.05P2<-( FTtable0.05P10.05P2_tmp + rotate_matrix_180(FTtable0.05P10.05P2_tmp) )/2
  data0.05P10.05P2_FT<-fisher.test(FTtable0.05P10.05P2, alternative ="two.sided")

  if(data0.05P10.05P2_FT[[3]][1] == 0) 
  {
    cat("   * There are not enough observations to perform a valid test of effect concordance.\n") 
  }
  if(data0.05P10.05P2_FT[[3]][1] > 0) 
  {
    ci<-paste(round(data0.05P10.05P2_FT[[2]][1], digits=4),"-",round(data0.05P10.05P2_FT[[2]][2], digits=4), sep="")
    data0.05P10.05P2_FTresults<-unname(c(paste(round(data0.05P10.05P2_FT[[3]][1], digits=4), " (", ci, ")", sep=""), format(data0.05P10.05P2_FT[[1]], digits=4)))
    names(data0.05P10.05P2_FTresults)<-c("  Odds ratio (95%CI)\t\t\t\t:", "  Fisher's exact test p-value (two-sided)\t:")
    write.table(data0.05P10.05P2_FTresults, quote = FALSE, col.names = "Test for association between effect direction in dataset1 and dataset2:\n")
    if(data0.05P10.05P2_FT[[3]][1] > 1) 
    { 
      cat("\n   * The SNP effects in dataset1 and dataset2 were POSITIVELY correlated.") 
      cat("\n   * If significant, this could indicate the presence of allelic effects")
      cat("\n     that increase risk for both traits.\n") 
    }
    if(data0.05P10.05P2_FT[[3]][1] < 1) 
    { 
      cat("\n   * The SNP effects in dataset1 and dataset2 were NEGATIVELY correlated") 
      cat("\n   * If significant, this could indicate the presence of allelic effects")
      cat("\n     that increase risk for one trait and decrease risk for the other trait.\n") 
    }
  }  
}

##############################################################################################################################

## Determine smallest p-values in dataset1 and dataset2:

minP1<-min(data1.0P1$P1)
minP2<-min(data1.0P1$P2)


## Test for pleiotropy and SNP effect concordance for SNPs genome-wide significant in dataset1 and nominally associated in dataset2:

if(minP1 <= 5.00e-08) 
{ 
  dataSIGP1<-subset(data1.0P1, P1 <= 5.00e-08) 
  data0.05P2<-subset(data1.0P1, P2 <= 0.05) 
  dataSIGP10.05P2<-subset(dataSIGP1, P2 <= 0.05) 

  dataSIGP10.05P2_BT<-binom.test(nrow(dataSIGP10.05P2),nrow(dataSIGP1), alternative ="two.sided", p = nrow(data0.05P2)/nrow(data1.0P1))
  ci<-paste(round(dataSIGP10.05P2_BT[[4]][1], digits=4),"-",round(dataSIGP10.05P2_BT[[4]][2], digits=4), sep="")
  dataSIGP10.05P2_BTresults<-unname(c(dataSIGP10.05P2_BT[[2]], dataSIGP10.05P2_BT[[1]], paste(round(dataSIGP10.05P2_BT[[5]], digits=4), " (", ci, ")", sep=""), round(dataSIGP10.05P2_BT[[6]], digits=4), format(dataSIGP10.05P2_BT[[3]], digits=4)))
  names(dataSIGP10.05P2_BTresults)<-c("  SNPs with P1 <= 5.00e-08 and P2 <= 1.00\t:", "  SNPs with P1 <= 5.00e-08 and P2 <= 0.05\t:", "  Observed proportion (95%CI)\t\t\t:", "  Expected proportion\t\t\t\t:", "  Exact binomial test p-value  (two-sided)\t:")

## Write out secondary results

  cat("\n___________________________________________________________________________________________________________________________________________________________________\n\n")

  cat("\nTests for genetic overlap between genome-wide significant dataset1 SNPs and dataset2 SNPs with P <= 0.05\n") 
  cat("\nSNPs with P1 <= 5e-08 and P2 <= 0.05\n") 

  write.table(dataSIGP10.05P2_BTresults, quote = FALSE, col.names = "\nTest for overlap of associated effects in dataset1 and dataset2 (pleiotropy):\n")
  if(unname(dataSIGP10.05P2_BT[[1]]) == 0) 
  { 
    cat("\n   * None of the genome-wide significant SNPs in dataset1 were nominally associated in dataset2.") 
    cat("\n   * If significant, this is strange and difficult to explain...\n") 
  }
  if(unname(dataSIGP10.05P2_BT[[1]]) > 0) 
  { 
    if(dataSIGP10.05P2_BT[[5]] > dataSIGP10.05P2_BT[[6]]) 
    { 
      cat("\n   * The number of SNPs associated in both datasets was MORE than expected.") 
      cat("\n   * If significant, this could indicate the presence of pleiotropy")
      cat("\n     (i.e., some genetic variants influence both traits).\n") 
    }
    if(dataSIGP10.05P2_BT[[5]] < dataSIGP10.05P2_BT[[6]]) 
    { 
      cat("\n   * The number of SNPs associated in both datasets was LESS than expected.") 
      cat("\n   * If significant, this is strange and difficult to explain...\n") 
    }

    cat("\n\nCross tabulation of effect direction in dataset1 (EFF1) versus dataset2 (EFF2):\n\n")

#    write.ftable(ftable(dataSIGP10.05P2[c("EFF1","EFF2")]), quote = FALSE)
#    cat("\n\n")

#    dataSIGP10.05P2_FT<-fisher.test(table(dataSIGP10.05P2[c("EFF1","EFF2")]), alternative ="two.sided")

  FTftableSIGP10.05P2_tmp<-ftable(dataSIGP10.05P2[c("EFF1","EFF2")])
  FTftableSIGP10.05P2<-( FTftableSIGP10.05P2_tmp + rotate_matrix_180(FTftableSIGP10.05P2_tmp) )/2
  write.ftable(FTftableSIGP10.05P2, quote = FALSE)
  cat("\n\n")

  FTtableSIGP10.05P2_tmp<-table(dataSIGP10.05P2[c("EFF1","EFF2")])
  FTtableSIGP10.05P2<-( FTtableSIGP10.05P2_tmp + rotate_matrix_180(FTtableSIGP10.05P2_tmp) )/2
  dataSIGP10.05P2_FT<-fisher.test(FTtableSIGP10.05P2, alternative ="two.sided")

    if(dataSIGP10.05P2_FT[[3]][1] == 0) 
    {
      cat("   * There are not enough observations to perform a valid test of effect concordance.\n") 
    }
    if(dataSIGP10.05P2_FT[[3]][1] > 0) 
    {
      ci<-paste(round(dataSIGP10.05P2_FT[[2]][1], digits=4),"-",round(dataSIGP10.05P2_FT[[2]][2], digits=4), sep="")
      dataSIGP10.05P2_FTresults<-unname(c(paste(round(dataSIGP10.05P2_FT[[3]][1], digits=4), " (", ci, ")", sep=""), format(dataSIGP10.05P2_FT[[1]], digits=4)))
      names(dataSIGP10.05P2_FTresults)<-c("  Odds ratio (95%CI)\t\t\t\t:", "  Fisher's exact test p-value (two-sided)\t:")
      write.table(dataSIGP10.05P2_FTresults, quote = FALSE, col.names = "Test for association between effect direction in dataset1 and dataset2:\n")
      if(dataSIGP10.05P2_FT[[3]][1] > 1) 
      { 
        cat("\n   * The SNP effects in dataset1 and dataset2 were POSITIVELY correlated.") 
        cat("\n   * If significant, this could indicate the presence of allelic effects")
        cat("\n     that increase risk for both traits.\n") 
      }
      if(dataSIGP10.05P2_FT[[3]][1] < 1) 
      { 
        cat("\n   * The SNP effects in dataset1 and dataset2 were NEGATIVELY correlated") 
        cat("\n   * If significant, this could indicate the presence of allelic effects")
        cat("\n     that increase risk for one trait and decrease risk for the other trait.\n") 
      }
    }  
  }
}

##############################################################################################################################

## Test for pleiotropy and SNP effect concordance for SNPs genome-wide suggestive in dataset1 and nominally associated in dataset2:

if(minP1 <= 1.00e-05) 
{ 
  dataSUGP1<-subset(data1.0P1, P1 <= 1.00e-05) 
  data0.05P2<-subset(data1.0P1, P2 <= 0.05) 
  dataSUGP10.05P2<-subset(dataSUGP1, P2 <= 0.05) 

  dataSUGP10.05P2_BT<-binom.test(nrow(dataSUGP10.05P2),nrow(dataSUGP1), alternative ="two.sided", p = nrow(data0.05P2)/nrow(data1.0P1))
  ci<-paste(round(dataSUGP10.05P2_BT[[4]][1], digits=4),"-",round(dataSUGP10.05P2_BT[[4]][2], digits=4), sep="")
  dataSUGP10.05P2_BTresults<-unname(c(dataSUGP10.05P2_BT[[2]], dataSUGP10.05P2_BT[[1]], paste(round(dataSUGP10.05P2_BT[[5]], digits=4), " (", ci, ")", sep=""), round(dataSUGP10.05P2_BT[[6]], digits=4), format(dataSUGP10.05P2_BT[[3]], digits=4)))
  names(dataSUGP10.05P2_BTresults)<-c("  SNPs with P1 <= 1.00e-05 and P2 <= 1.00\t:", "  SNPs with P1 <= 1.00e-05 and P2 <= 0.05\t:", "  Observed proportion (95%CI)\t\t\t:", "  Expected proportion\t\t\t\t:", "  Exact binomial test p-value  (two-sided)\t:")

## Write out tertiary results

  cat("\n___________________________________________________________________________________________________________________________________________________________________\n\n")

  cat("\nTests for genetic overlap between genome-wide suggestive dataset1 SNPs and dataset2 SNPs with P <= 0.05\n") 
  cat("\nSNPs with P1 <= 1e-05 and P2 <= 0.05\n") 

  write.table(dataSUGP10.05P2_BTresults, quote = FALSE, col.names = "\nTest for overlap of associated effects in dataset1 and dataset2 (pleiotropy):\n")
  if(unname(dataSUGP10.05P2_BT[[1]]) == 0) 
  { 
    cat("\n   * None of the genome-wide suggestive SNPs in dataset1 were nominally associated in dataset2.") 
    cat("\n   * If significant, this is strange and difficult to explain...\n") 
  }
  if(unname(dataSUGP10.05P2_BT[[1]]) > 0) 
  { 
    if(dataSUGP10.05P2_BT[[5]] > dataSUGP10.05P2_BT[[6]]) 
    { 
      cat("\n   * The number of SNPs associated in both datasets was MORE than expected.") 
      cat("\n   * If significant, this could indicate the presence of pleiotropy")
      cat("\n     (i.e., some genetic variants influence both traits).\n") 
    }
    if(dataSUGP10.05P2_BT[[5]] < dataSUGP10.05P2_BT[[6]]) 
    { 
      cat("\n   * The number of SNPs associated in both datasets was LESS than expected.") 
      cat("\n   * If significant, this is strange and difficult to explain...\n") 
    }

    cat("\n\nCross tabulation of effect direction in dataset1 (EFF1) versus dataset2 (EFF2):\n\n")

#    write.ftable(ftable(dataSUGP10.05P2[c("EFF1","EFF2")]), quote = FALSE)
#    cat("\n\n")

#    dataSUGP10.05P2_FT<-fisher.test(table(dataSUGP10.05P2[c("EFF1","EFF2")]), alternative ="two.sided")

  FTftableSUGP10.05P2_tmp<-ftable(dataSUGP10.05P2[c("EFF1","EFF2")])
  FTftableSUGP10.05P2<-( FTftableSUGP10.05P2_tmp + rotate_matrix_180(FTftableSUGP10.05P2_tmp) )/2
  write.ftable(FTftableSUGP10.05P2, quote = FALSE)
  cat("\n\n")

  FTtableSUGP10.05P2_tmp<-table(dataSUGP10.05P2[c("EFF1","EFF2")])
  FTtableSUGP10.05P2<-( FTtableSUGP10.05P2_tmp + rotate_matrix_180(FTtableSUGP10.05P2_tmp) )/2
  dataSUGP10.05P2_FT<-fisher.test(FTtableSUGP10.05P2, alternative ="two.sided")

    if(dataSUGP10.05P2_FT[[3]][1] == 0) 
    {
      cat("   * There are not enough observations to perform a valid test of effect concordance.\n") 
    }
    if(dataSUGP10.05P2_FT[[3]][1] > 0) 
    {
      ci<-paste(round(dataSUGP10.05P2_FT[[2]][1], digits=4),"-",round(dataSUGP10.05P2_FT[[2]][2], digits=4), sep="")
      dataSUGP10.05P2_FTresults<-unname(c(paste(round(dataSUGP10.05P2_FT[[3]][1], digits=4), " (", ci, ")", sep=""), format(dataSUGP10.05P2_FT[[1]], digits=4)))
      names(dataSUGP10.05P2_FTresults)<-c("  Odds ratio (95%CI)\t\t\t\t:", "  Fisher's exact test p-value (two-sided)\t:")
      write.table(dataSUGP10.05P2_FTresults, quote = FALSE, col.names = "Test for association between effect direction in dataset1 and dataset2:\n")
      if(dataSUGP10.05P2_FT[[3]][1] > 1) 
      { 
        cat("\n   * The SNP effects in dataset1 and dataset2 were POSITIVELY correlated.") 
        cat("\n   * If significant, this could indicate the presence of allelic effects")
        cat("\n     that increase risk for both traits.\n") 
      }
      if(dataSUGP10.05P2_FT[[3]][1] < 1) 
      { 
        cat("\n   * The SNP effects in dataset1 and dataset2 were NEGATIVELY correlated") 
        cat("\n   * If significant, this could indicate the presence of allelic effects")
        cat("\n     that increase risk for one trait and decrease risk for the other trait.\n") 
      }
    }  
  }
}

##############################################################################################################################

## Analyse subset producing minimum PLEITROPY (Exact binomial test) p-value
## While the minimum PLEITROPY is consider post-hoc, the CONCORDANCE test is only performed ONCE
## This should give the maximum power to find a significant p-value for concordant effects via a single additional test

BTminArrayInd<-arrayInd(which.min(BTpvalues), dim(BTpvalues))
BTminP1<-PstepsALL[BTminArrayInd[1,1]]
BTminP2<-PstepsALL[BTminArrayInd[1,2]]

#dataBTminP1<-subset(data1.0P1, P1 <= BTminP1) 
#dataBTminP1minP2<-subset(dataBTminP1, P2 <= BTminP2) 

## Write out results

  dataBTminP1<-subset(data1.0P1, P1 <= BTminP1) 
  dataBTminP2<-subset(data1.0P1, P2 <= BTminP2) 
  dataBTminP1minP2<-subset(dataBTminP1, P2 <= BTminP2) 

  dataBTminP1Label<-paste("SNPs with P1 <= ", format(BTminP1, digits=3), " and P2 <= 1.00", sep="")
  dataBTminP1minP2Label<-paste("SNPs with P1 <= ", format(BTminP1, digits=3), " and P2 <= ", format(BTminP2, digits=3), sep="")

  dataBTminP1LabelName<-paste("  ", dataBTminP1Label, "\t\t:", sep="") 
  dataBTminP1minP2LabelName<-paste("  ", dataBTminP1minP2Label, "\t\t:", sep="") 

  dataBTminP1minP2_BT<-binom.test(nrow(dataBTminP1minP2),nrow(dataBTminP1), alternative ="two.sided", p = nrow(dataBTminP2)/nrow(data1.0P1))
  ci<-paste(round(dataBTminP1minP2_BT[[4]][1], digits=4),"-",round(dataBTminP1minP2_BT[[4]][2], digits=4), sep="")
  dataBTminP1minP2_BTresults<-unname(c(dataBTminP1minP2_BT[[2]], dataBTminP1minP2_BT[[1]], paste(round(dataBTminP1minP2_BT[[5]], digits=4), " (", ci, ")", sep=""), round(dataBTminP1minP2_BT[[6]], digits=4), format(dataBTminP1minP2_BT[[3]], digits=4)))
  names(dataBTminP1minP2_BTresults)<-c(dataBTminP1LabelName, dataBTminP1minP2LabelName, "  Observed proportion (95%CI)\t\t\t:", "  Expected proportion\t\t\t\t:", "  Exact binomial test p-value  (two-sided)\t:")

  cat("\n___________________________________________________________________________________________________________________________________________________________________\n\n")

  cat("\nTests for genetic overlap in subset producing the minimum exact binomial test ('pleiotropy') p-value\n")
#  cat("\n ## Note: if you have multiple subsets with p = 0 (< 2.22e-308) the below subset may not be the minimum, ##")
#  cat("\n ##       to identify the minimum you will need to examine the raw data in griddata.txt ##\n")

  dataBTminP1minP2Label<-paste("SNPs with P1 <= ", format(BTminP1, digits=3), " and P2 <= ", format(BTminP2, digits=3), sep="")
  cat("\n")
  cat(dataBTminP1minP2Label)
  cat("\n") 

  write.table(dataBTminP1minP2_BTresults, quote = FALSE, col.names = "\nTest for overlap of associated effects in dataset1 and dataset2 (pleiotropy):\n")
  if(unname(dataBTminP1minP2_BT[[1]]) == 0) 
  { 
    cat("\n   * None of the SNPs in dataset1 were in dataset2.") 
    cat("\n   * If significant, this is strange and difficult to explain...\n") 
  }
  if(unname(dataBTminP1minP2_BT[[1]]) > 0) 
  { 
    if(dataBTminP1minP2_BT[[5]] > dataBTminP1minP2_BT[[6]]) 
    { 
      cat("\n   * The number of SNPs associated in both datasets was MORE than expected.") 
      cat("\n   * If significant, this could indicate the presence of pleiotropy")
      cat("\n     (i.e., some genetic variants influence both traits).\n") 
    }
    if(dataBTminP1minP2_BT[[5]] < dataBTminP1minP2_BT[[6]]) 
    { 
      cat("\n   * The number of SNPs associated in both datasets was LESS than expected.") 
      cat("\n   * If significant, this is strange and difficult to explain...\n") 
    }

    cat("\n\nCross tabulation of effect direction in dataset1 (EFF1) versus dataset2 (EFF2):\n\n")

#    write.ftable(ftable(dataBTminP1minP2[c("EFF1","EFF2")]), quote = FALSE)
#    cat("\n\n")
#    dataBTminP1minP2_FT<-fisher.test(table(dataBTminP1minP2[c("EFF1","EFF2")]), alternative ="two.sided")


  FTftableBTminP1minP2_tmp<-ftable(dataBTminP1minP2[c("EFF1","EFF2")])
  FTftableBTminP1minP2<-( FTftableBTminP1minP2_tmp + rotate_matrix_180(FTftableBTminP1minP2_tmp) )/2
  
  write.ftable(FTftableBTminP1minP2, quote = FALSE)
  cat("\n\n")

  FTtableBTminP1minP2_tmp<-table(dataBTminP1minP2[c("EFF1","EFF2")])
  FTtableBTminP1minP2<-( FTtableBTminP1minP2_tmp + rotate_matrix_180(FTtableBTminP1minP2_tmp) )/2
  dataBTminP1minP2_FT<-fisher.test(FTtableBTminP1minP2, alternative ="two.sided")

    if(dataBTminP1minP2_FT[[3]][1] == 0) 
    {
      cat("   * There are not enough observations to perform a valid test of effect concordance.\n") 
    }
    if(dataBTminP1minP2_FT[[3]][1] > 0) 
    {
      ci<-paste(round(dataBTminP1minP2_FT[[2]][1], digits=4),"-",round(dataBTminP1minP2_FT[[2]][2], digits=4), sep="")
      dataBTminP1minP2_FTresults<-unname(c(paste(round(dataBTminP1minP2_FT[[3]][1], digits=4), " (", ci, ")", sep=""), format(dataBTminP1minP2_FT[[1]], digits=4)))
      names(dataBTminP1minP2_FTresults)<-c("  Odds ratio (95%CI)\t\t\t\t:", "  Fisher's exact test p-value (two-sided)\t:")
      write.table(dataBTminP1minP2_FTresults, quote = FALSE, col.names = "Test for association between effect direction in dataset1 and dataset2:\n")
      if(dataBTminP1minP2_FT[[3]][1] > 1) 
      { 
        cat("\n   * The SNP effects in dataset1 and dataset2 were POSITIVELY correlated.") 
        cat("\n   * If significant, this could indicate the presence of allelic effects")
        cat("\n     that increase risk for both traits.\n") 
      }
      if(dataBTminP1minP2_FT[[3]][1] < 1) 
      { 
        cat("\n   * The SNP effects in dataset1 and dataset2 were NEGATIVELY correlated") 
        cat("\n   * If significant, this could indicate the presence of allelic effects")
        cat("\n     that increase risk for one trait and decrease risk for the other trait.\n") 
      }
    }  
  }

##############################################################################################################################

## Analyse subset producing minimum CONCORDANCE (Fisher's Exact Test) p-value
## This is strictly post-hoc to find the minimum

FTminArrayInd<-arrayInd(which.min(FTpvalues), dim(FTpvalues))
FTminP1<-PstepsALL[FTminArrayInd[1,1]]
FTminP2<-PstepsALL[FTminArrayInd[1,2]]

#dataFTminP1<-subset(data1.0P1, P1 <= FTminP1) 
#dataFTminP1minP2<-subset(dataFTminP1, P2 <= FTminP2) 

## Write out results

  dataFTminP1<-subset(data1.0P1, P1 <= FTminP1) 
  dataFTminP2<-subset(data1.0P1, P2 <= FTminP2) 
  dataFTminP1minP2<-subset(dataFTminP1, P2 <= FTminP2) 

  dataFTminP1Label<-paste("SNPs with P1 <= ", format(FTminP1, digits=3), " and P2 <= 1.00", sep="")
  dataFTminP1minP2Label<-paste("SNPs with P1 <= ", format(FTminP1, digits=3), " and P2 <= ", format(FTminP2, digits=3), sep="")

  dataFTminP1LabelName<-paste("  ", dataFTminP1Label, "\t\t:", sep="") 
  dataFTminP1minP2LabelName<-paste("  ", dataFTminP1minP2Label, "\t\t:", sep="") 

  dataFTminP1minP2_BT<-binom.test(nrow(dataFTminP1minP2),nrow(dataFTminP1), alternative ="two.sided", p = nrow(dataFTminP2)/nrow(data1.0P1))
  ci<-paste(round(dataFTminP1minP2_BT[[4]][1], digits=4),"-",round(dataFTminP1minP2_BT[[4]][2], digits=4), sep="")
  dataFTminP1minP2_BTresults<-unname(c(dataFTminP1minP2_BT[[2]], dataFTminP1minP2_BT[[1]], paste(round(dataFTminP1minP2_BT[[5]], digits=4), " (", ci, ")", sep=""), round(dataFTminP1minP2_BT[[6]], digits=4), format(dataFTminP1minP2_BT[[3]], digits=4)))
  names(dataFTminP1minP2_BTresults)<-c(dataFTminP1LabelName, dataFTminP1minP2LabelName, "  Observed proportion (95%CI)\t\t\t:", "  Expected proportion\t\t\t\t:", "  Exact binomial test p-value  (two-sided)\t:")

  cat("\n___________________________________________________________________________________________________________________________________________________________________\n\n")

  cat("\nTests for genetic overlap in subset producing the minimum Fisher's exact test (effect correlation) p-value\n")
#  cat("\n ## Note: if you have multiple subsets with p = 0 (< 2.22e-308) the below subset may not be the minimum, ##")
#  cat("\n ##       to identify the minimum you will need to examine the raw data in griddata.txt ##\n")
  dataFTminP1minP2Label<-paste("SNPs with P1 <= ", format(FTminP1, digits=3), " and P2 <= ", format(FTminP2, digits=3), sep="")
  cat("\n")
  cat(dataFTminP1minP2Label)
  cat("\n") 

  write.table(dataFTminP1minP2_BTresults, quote = FALSE, col.names = "\nTest for overlap of associated effects in dataset1 and dataset2 (pleiotropy):\n")
  if(unname(dataFTminP1minP2_BT[[1]]) == 0) 
  { 
    cat("\n   * None of the SNPs in dataset1 were in dataset2.") 
    cat("\n   * If significant, this is strange and difficult to explain...\n") 
  }
  if(unname(dataFTminP1minP2_BT[[1]]) > 0) 
  { 
    if(dataFTminP1minP2_BT[[5]] > dataFTminP1minP2_BT[[6]]) 
    { 
      cat("\n   * The number of SNPs associated in both datasets was MORE than expected.") 
      cat("\n   * If significant, this could indicate the presence of pleiotropy")
      cat("\n     (i.e., some genetic variants influence both traits).\n") 
    }
    if(dataFTminP1minP2_BT[[5]] < dataFTminP1minP2_BT[[6]]) 
    { 
      cat("\n   * The number of SNPs associated in both datasets was LESS than expected.") 
      cat("\n   * If significant, this is strange and difficult to explain...\n") 
    }

    cat("\n\nCross tabulation of effect direction in dataset1 (EFF1) versus dataset2 (EFF2):\n\n")

#    write.ftable(ftable(dataFTminP1minP2[c("EFF1","EFF2")]), quote = FALSE)
#    cat("\n\n")

#    dataFTminP1minP2_FT<-fisher.test(table(dataFTminP1minP2[c("EFF1","EFF2")]), alternative ="two.sided")

  FTftableFTminP1minP2_tmp<-ftable(dataFTminP1minP2[c("EFF1","EFF2")])
  FTftableFTminP1minP2<-( FTftableFTminP1minP2_tmp + rotate_matrix_180(FTftableFTminP1minP2_tmp) )/2
  write.ftable(FTftableFTminP1minP2, quote = FALSE)
  cat("\n\n")

  FTtableFTminP1minP2_tmp<-table(dataFTminP1minP2[c("EFF1","EFF2")])
  FTtableFTminP1minP2<-( FTtableFTminP1minP2_tmp + rotate_matrix_180(FTtableFTminP1minP2_tmp) )/2
  dataFTminP1minP2_FT<-fisher.test(FTtableFTminP1minP2, alternative ="two.sided")


    if(dataFTminP1minP2_FT[[3]][1] == 0) 
    {
      cat("   * There are not enough observations to perform a valid test of effect concordance.\n") 
    }
    if(dataFTminP1minP2_FT[[3]][1] > 0) 
    {
      ci<-paste(round(dataFTminP1minP2_FT[[2]][1], digits=4),"-",round(dataFTminP1minP2_FT[[2]][2], digits=4), sep="")
      dataFTminP1minP2_FTresults<-unname(c(paste(round(dataFTminP1minP2_FT[[3]][1], digits=4), " (", ci, ")", sep=""), format(dataFTminP1minP2_FT[[1]], digits=4)))
      names(dataFTminP1minP2_FTresults)<-c("  Odds ratio (95%CI)\t\t\t\t:", "  Fisher's exact test p-value (two-sided)\t:")
      write.table(dataFTminP1minP2_FTresults, quote = FALSE, col.names = "Test for association between effect direction in dataset1 and dataset2:\n")
      if(dataFTminP1minP2_FT[[3]][1] > 1) 
      { 
        cat("\n   * The SNP effects in dataset1 and dataset2 were POSITIVELY correlated.") 
        cat("\n   * If significant, this could indicate the presence of allelic effects")
        cat("\n     that increase risk for both traits.\n") 
      }
      if(dataFTminP1minP2_FT[[3]][1] < 1) 
      { 
        cat("\n   * The SNP effects in dataset1 and dataset2 were NEGATIVELY correlated") 
        cat("\n   * If significant, this could indicate the presence of allelic effects")
        cat("\n     that increase risk for one trait and decrease risk for the other trait.\n") 
      }
    }  
  }
  cat("\n___________________________________________________________________________________________________________________________________________________________________\n\n")
  cat("\n ## Notes: 1) a p-value of '0' is actually < 2.22e-308                                              ##")
  cat("\n ##        2) if you have multiple subsets with p = 0, to identify the true minimum binomial and    ##")
  cat("\n ##           Fisher's test subsets, you will need to examine the raw data in griddata.txt          ##")
  cat("\n ##        3) values of 'Inf' represent infinity, indicating the calculation could not be performed ##\n\n")


sink()

